In [504]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import validation_curve
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.ensemble import RandomForestClassifier

In [505]:
%pwd

'/Users/terryjiang'

In [506]:
bank_bal=pd.read_csv('data.csv.zip')
bank_bal

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0             1                                           0.370594          
1             1                                           0.464291          
2             1                                           0.426071          
3             1                                           0.399844          
4             1                                           0.465022          
...         ...                                                ...          
6814          0                                           0.493687          
6815          0                                           0.475162          
6816          0                                           0.472725          
6817          0                                           0.506264          
6818          0                                           0.493053          

       ROA(A) before interest and % after tax  \
0                                    0.424389   
1                                    0.538214   
2                                    0.499019   
3                                    0.451265   
4                                    0.538432   
...                                       ...   
6814                                 0.539468   
6815                                 0.538269   
6816                                 0.533744   
6817                                 0.559911   
6818                                 0.570105   

       ROA(B) before interest and depreciation after tax  \
0                                              0.405750    
1                                              0.516730    
2                                              0.472295    
3                                              0.457733    
4                                              0.522298    
...                                                 ...    
6814                                           0.543230    
6815                                           0.524172    
6816                                           0.520638    
6817                                           0.554045    
6818                                           0.549548    

       Operating Gross Margin   Realized Sales Gross Margin  \
0                    0.601457                      0.601457   
1                    0.610235                      0.610235   
2                    0.601450                      0.601364   
3                    0.583541                      0.583541   
4                    0.598783                      0.598783   
...                       ...                           ...   
6814                 0.604455                      0.604462   
6815                 0.598308                      0.598308   
6816                 0.610444                      0.610213   
6817                 0.607850                      0.607850   
6818                 0.627409                      0.627409   

       Operating Profit Rate   Pre-tax net Interest Rate  \
0                   0.998969                    0.796887   
1                   0.998946                    0.797380   
2                   0.998857                    0.796403   
3                   0.998700                    0.796967   
4                   0.998973                    0.797366   
...                      ...                         ...   
6814                0.998992                    0.797409   
6815                0.998992                    0.797414   
6816                0.998984                    0.797401   
6817                0.999074                    0.797500   
6818                0.998080                    0.801987   

       After-tax net Interest Rate  \
0                         0.808809   
1                         0.809301   
2                         0.808388   
3                         0.808966   
4                         0.809304   
...                            ...   
6814                      0

# Data Sampling

In [507]:
bank_bal=bank_bal.groupby('Bankrupt?',group_keys=False).apply(lambda x: x.sample(1000,replace=True,random_state=0))
bank_bal['Bankrupt?'].value_counts()

0    1000
1    1000
Name: Bankrupt?, dtype: int64

In [508]:
bank_bal

Bankrupt?   ROA(C) before interest and depreciation before interest  \
2893          0                                           0.616195          
2765          0                                           0.582850          
1731          0                                           0.500463          
3434          0                                           0.475455          
5125          0                                           0.518403          
...         ...                                                ...          
2149          1                                           0.412616          
4264          1                                           0.407400          
1752          1                                           0.448447          
2704          1                                           0.495539          
0             1                                           0.370594          

       ROA(A) before interest and % after tax  \
2893                                 0.655037   
2765                                 0.621784   
1731                                 0.545464   
3434                                 0.545464   
5125                                 0.578772   
...                                       ...   
2149                                 0.422209   
4264                                 0.442652   
1752                                 0.463694   
2704                                 0.545901   
0                                    0.424389   

       ROA(B) before interest and depreciation after tax  \
2893                                           0.642915    
2765                                           0.622196    
1731                                           0.547620    
3434                                           0.532684    
5125                                           0.562129    
...                                                 ...    
2149                                           0.453557    
4264                                           0.438086    
1752                                           0.486000    
2704                                           0.547674    
0                                              0.405750    

       Operating Gross Margin   Realized Sales Gross Margin  \
2893                 0.616325                      0.616325   
2765                 0.642586                      0.642586   
1731                 0.605198                      0.605198   
3434                 0.598661                      0.598675   
5125                 0.599158                      0.599165   
...                       ...                           ...   
2149                 0.598358                      0.598358   
4264                 0.609349                      0.609320   
1752                 0.594027                      0.594027   
2704                 0.619770                      0.619770   
0                    0.601457                      0.601457   

       Operating Profit Rate   Pre-tax net Interest Rate  \
2893                0.999192                    0.797712   
2765                0.999160                    0.797665   
1731                0.999033                    0.797413   
3434                0.998970                    0.797396   
5125                0.999015                    0.797446   
...                      ...                         ...   
2149                0.998916                    0.796831   
4264                0.998786                    0.797106   
1752                0.998887                    0.797178   
2704                0.999041                    0.797473   
0                   0.998969                    0.796887   

       After-tax net Interest Rate  \
2893                      0.809545   
2765                      0.809535   
1731                      0.809341   
3434                      0.809328   
5125                      0.809354   
...                            ...   
2149                      0

# Logistic Regression¶

In [509]:
bank_bal[bank_bal['Bankrupt?']==1].describe().round(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count     1000.0                                            1000.00          
mean         1.0                                               0.42          
std          0.0                                               0.08          
min          1.0                                               0.02          
25%          1.0                                               0.39          
50%          1.0                                               0.44          
75%          1.0                                               0.47          
max          1.0                                               0.58          

        ROA(A) before interest and % after tax  \
count                                  1000.00   
mean                                      0.45   
std                                       0.11   
min                                       0.00   
25%                                       0.43   
50%                                       0.49   
75%                                       0.53   
max                                       0.58   

        ROA(B) before interest and depreciation after tax  \
count                                            1000.00    
mean                                                0.46    
std                                                 0.09    
min                                                 0.03    
25%                                                 0.43    
50%                                                 0.49    
75%                                                 0.52    
max                                                 0.62    

        Operating Gross Margin   Realized Sales Gross Margin  \
count                  1000.00                       1000.00   
mean                      0.60                          0.60   
std                       0.01                          0.01   
min                       0.53                          0.53   
25%                       0.59                          0.59   
50%                       0.60                          0.60   
75%                       0.60                          0.60   
max                       0.67                          0.67   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count                 1000.00                     1000.00   
mean                     1.00                        0.80   
std                      0.00                        0.00   
min                      0.99                        0.76   
25%                      1.00                        0.80   
50%                      1.00                        0.80   
75%                      1.00                        0.80   
max                      1.00                        0.80   

        After-tax net Interest Rate  \
count                       1000.00   
mean                           0.81   
std                            0.01   
min                            0.76   
25%                            0.81   
50%                            0.81   
75%                            0.81   
max                            0.81   

        Non-industry income and expenditure/revenue  ...  \
count                                       1000.00  ...   
mean                                           0.30  ...   
std                                            0.01  ...   
min                                            0.24  ...   
25%                                            0.30  ...   
50%                                            0.30  ...   
75%                                            0.30  ...   
max                                            0.31  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                      1000.00                1.000000e+03   
mean                          0.73                1.276100e+08   
std                           0.09                1.012655e+09   
min                

In [510]:
bank_bal[bank_bal['Bankrupt?']==0].describe().round(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count     1000.0                                            1000.00          
mean         0.0                                               0.51          
std          0.0                                               0.06          
min          0.0                                               0.23          
25%          0.0                                               0.48          
50%          0.0                                               0.51          
75%          0.0                                               0.54          
max          0.0                                               1.00          

        ROA(A) before interest and % after tax  \
count                                  1000.00   
mean                                      0.56   
std                                       0.06   
min                                       0.16   
25%                                       0.54   
50%                                       0.56   
75%                                       0.59   
max                                       0.95   

        ROA(B) before interest and depreciation after tax  \
count                                            1000.00    
mean                                                0.56    
std                                                 0.06    
min                                                 0.21    
25%                                                 0.53    
50%                                                 0.56    
75%                                                 0.59    
max                                                 0.96    

        Operating Gross Margin   Realized Sales Gross Margin  \
count                  1000.00                       1000.00   
mean                      0.61                          0.61   
std                       0.01                          0.01   
min                       0.45                          0.45   
25%                       0.60                          0.60   
50%                       0.61                          0.61   
75%                       0.61                          0.61   
max                       0.66                          0.66   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count                 1000.00                     1000.00   
mean                     1.00                        0.80   
std                      0.00                        0.00   
min                      0.97                        0.75   
25%                      1.00                        0.80   
50%                      1.00                        0.80   
75%                      1.00                        0.80   
max                      1.00                        0.80   

        After-tax net Interest Rate  \
count                       1000.00   
mean                           0.81   
std                            0.00   
min                            0.77   
25%                            0.81   
50%                            0.81   
75%                            0.81   
max                            0.81   

        Non-industry income and expenditure/revenue  ...  \
count                                       1000.00  ...   
mean                                           0.30  ...   
std                                            0.00  ...   
min                                            0.28  ...   
25%                                            0.30  ...   
50%                                            0.30  ...   
75%                                            0.30  ...   
max                                            0.31  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                      1000.00                1.000000e+03   
mean                          0.81                1.651000e+07   
std                           0.03                3.742320e+08   
min                

## controlling the complexity of log regression, using parameter 'c'

In [511]:
bank_bal=bank_bal.sample(frac=1, random_state=0)
bank_bal.head(1)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
4191          0                                           0.372934          

       ROA(A) before interest and % after tax  \
4191                                 0.431313   

       ROA(B) before interest and depreciation after tax  \
4191                                           0.414904    

       Operating Gross Margin   Realized Sales Gross Margin  \
4191                 0.594322                      0.594135   

       Operating Profit Rate   Pre-tax net Interest Rate  \
4191                0.998888                    0.797214   

       After-tax net Interest Rate  \
4191                      0.809148   

       Non-industry income and expenditure/revenue  ...  \
4191                                      0.303388  ...   

       Net Income to Total Assets   Total assets to GNP price  \
4191                     0.723812                    0.005107   

       No-credit Interval   Gross Profit to Sales  \
4191             0.623694                0.594319   

       Net Income to Stockholder's Equity   Liability to Equity  \
4191                             0.828935              0.290253   

       Degree of Financial Leverage (DFL)  \
4191                             0.026745   

       Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
4191                                           0.564931                   1   

       Equity to Liability  
4191              0.016448  

[1 rows x 96 columns]

In [512]:
X_bank, y_bank=bank_bal.iloc[:,1:], bank_bal['Bankrupt?'] 
display(X_bank.head(2))
display(y_bank.head(2))

ROA(C) before interest and depreciation before interest  \
4191                                           0.372934          
1447                                           0.479745          

       ROA(A) before interest and % after tax  \
4191                                 0.431313   
1447                                 0.545028   

       ROA(B) before interest and depreciation after tax  \
4191                                           0.414904    
1447                                           0.530060    

       Operating Gross Margin   Realized Sales Gross Margin  \
4191                 0.594322                      0.594135   
1447                 0.619020                      0.618235   

       Operating Profit Rate   Pre-tax net Interest Rate  \
4191                0.998888                    0.797214   
1447                0.999088                    0.797430   

       After-tax net Interest Rate  \
4191                      0.809148   
1447                      0.809334   

       Non-industry income and expenditure/revenue  \
4191                                      0.303388   
1447                                      0.303347   

       Continuous interest rate (after tax)  ...   Net Income to Total Assets  \
4191                               0.781377  ...                     0.723812   
1447                               0.781579  ...                     0.798701   

       Total assets to GNP price   No-credit Interval   Gross Profit to Sales  \
4191                    0.005107             0.623694                0.594319   
1447                    0.003045             0.623882                0.619021   

       Net Income to Stockholder's Equity   Liability to Equity  \
4191                             0.828935              0.290253   
1447                             0.840290              0.281135   

       Degree of Financial Leverage (DFL)  \
4191                             0.026745   
1447                             0.028226   

       Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
4191                                           0.564931                   1   
1447                                           0.568060                   1   

       Equity to Liability  
4191              0.016448  
1447              0.025232  

[2 rows x 95 columns]

4191    0
1447    1
Name: Bankrupt?, dtype: int64

## Feature Selection

In [513]:
from sklearn.tree import DecisionTreeClassifier

In [514]:
dt=DecisionTreeClassifier(random_state=0)
dt.fit(X_bank,y_bank)

DecisionTreeClassifier(random_state=0)

In [515]:
sum(dt.feature_importances_>.01)

17

In [516]:
X_bank_sel=X_bank[X_bank.columns[dt.feature_importances_>.01]]
X_bank_sel.head()

Realized Sales Gross Margin   Operating Profit Rate  \
4191                      0.594135                0.998888   
1447                      0.618235                0.999088   
2496                      0.578165                0.998648   
4323                      0.607684                0.999049   
5500                      0.599648                0.998970   

       Continuous interest rate (after tax)   Operating Expense Rate  \
4191                               0.781377             9.000000e+09   
1447                               0.781579             2.763712e-04   
2496                               0.780017             7.370000e+08   
4323                               0.781726             1.453551e-04   
5500                               0.781359             9.620000e+09   

       Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
4191         0.458792                0.000339                 0.630462   
1447         0.459837                0.000437                 0.633790   
2496         0.458980                0.000331                 0.625583   
4323         0.461195                0.000705                 0.630818   
5500         0.460554                0.000379                 0.629533   

       Borrowing dependency   Net Worth Turnover Rate (times)  \
4191               0.377531                          0.081935   
1447               0.379239                          0.021774   
2496               0.514239                          0.017742   
4323               0.371526                          0.059355   
5500               0.395686                          0.048871   

       Allocation rate per person   Inventory/Working Capital  \
4191                     0.007732                    0.283268   
1447                     0.020430                    0.277213   
2496                     0.621377                    0.276974   
4323                     0.001240                    0.277134   
5500                     0.003990                    0.276440   

       Inventory/Current Liability   Retained Earnings to Total Assets  \
4191                  1.009751e-03                            0.907492   
1447                  3.670025e-03                            0.932293   
2496                  6.440000e+08                            0.912139   
4323                  4.630348e-03                            0.948180   
5500                  3.269891e-03                            0.878007   

       Cash Turnover Rate   Current Liability to Liability  \
4191         4.260000e+09                         0.903625   
1447         1.893589e-04                         0.680898   
2496         3.165289e-04                         0.049582   
4323         5.310000e+08                         0.829895   
5500         2.000000e+07                         0.683642   

       Total assets to GNP price   Equity to Liability  
4191                    0.005107              0.016448  
1447                    0.003045              0.025232  
2496                    0.387361              0.011326  
4323                    0.001079              0.030965  
5500                    0.001614              0.014274

## transform the features

In [517]:
scaler1=MinMaxScaler()
X_bank_trns=scaler1.fit_transform(X_bank_sel)
X_bank_trns

array([[0.67029143, 0.97094304, 0.90776909, ..., 0.89859766, 0.        ,
        0.01331719],
       [0.78217954, 0.97857407, 0.9117358 , ..., 0.66425108, 0.        ,
        0.02267398],
       [0.59614548, 0.96180078, 0.88109493, ..., 0.        , 0.        ,
        0.00786133],
       ...,
       [0.7761234 , 0.98249092, 0.91249831, ..., 0.8603324 , 0.        ,
        0.05813957],
       [0.81436745, 0.98252177, 0.91479961, ..., 0.91978202, 0.        ,
        0.13811285],
       [0.78933985, 0.98319587, 0.91669075, ..., 0.6758211 , 0.        ,
        0.03470609]])

## validation curve functions

In [518]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_trns, y_bank, test_size=0.2, random_state=0)

In [519]:
train_scores_log_reg, test_scores_log_reg=validation_curve(LogisticRegression(penalty='l1', solver='saga', max_iter=100000), X_train, y_train, param_name='C',
                                           param_range=[0.01,0.05,1,5,10,20], cv=4)

In [520]:
train_scores_log_reg.mean(axis=1).round(4)

array([0.4975, 0.7677, 0.8321, 0.8621, 0.8602, 0.861 ])

In [521]:
test_scores_log_reg.mean(axis=1).round(4)

array([0.4975, 0.77  , 0.8212, 0.8525, 0.8525, 0.8544])

In [522]:
log_reg=LogisticRegression(max_iter=1000, C=100)
log_reg.fit(X_train, y_train)

LogisticRegression(C=100, max_iter=1000)

In [523]:
print('log reg acc on train: {:.2%}'.format(log_reg.score(X_train, y_train)))
print('log reg acc on test: {:.2%}'.format(log_reg.score(X_test, y_test)))

log reg acc on train: 85.75%
log reg acc on test: 85.25%


In [524]:
log_reg.coef_

array([[ -7.18913619,  13.97367307, -11.11917622,  -0.14566533,
        -17.27773196,   1.16929683,   2.64163736,   3.56718348,
         -2.44283466,   3.66979635,  -9.88782096,   3.48182077,
        -14.59778957,  -0.33038749,  -0.24396249,  -2.83724605,
        -43.8013668 ]])

In [525]:
p1=[0.2,0.4,0.5,0.1,0.4,0.3,0.2,0.5,0.2,0.5,0.5,0.2,0.2,0.4,0.5,0.2,0.1]
log_reg.predict([p1])

array([1])

In [526]:
import numpy as np
np.set_printoptions(suppress=True)

In [527]:
log_reg.predict_proba([p1]).round(4)

array([[0.0184, 0.9816]])

In [528]:
log_reg.classes_

array([0, 1])

In [529]:
log_reg.coef_.round(4)

array([[ -7.1891,  13.9737, -11.1192,  -0.1457, -17.2777,   1.1693,
          2.6416,   3.5672,  -2.4428,   3.6698,  -9.8878,   3.4818,
        -14.5978,  -0.3304,  -0.244 ,  -2.8372, -43.8014]])

In [530]:
log_reg.intercept_.round(4)

array([20.6723])

# SVM 

In [531]:
X_bank_trns

array([[0.67029143, 0.97094304, 0.90776909, ..., 0.89859766, 0.        ,
        0.01331719],
       [0.78217954, 0.97857407, 0.9117358 , ..., 0.66425108, 0.        ,
        0.02267398],
       [0.59614548, 0.96180078, 0.88109493, ..., 0.        , 0.        ,
        0.00786133],
       ...,
       [0.7761234 , 0.98249092, 0.91249831, ..., 0.8603324 , 0.        ,
        0.05813957],
       [0.81436745, 0.98252177, 0.91479961, ..., 0.91978202, 0.        ,
        0.13811285],
       [0.78933985, 0.98319587, 0.91669075, ..., 0.6758211 , 0.        ,
        0.03470609]])

In [532]:
svm1=LinearSVC(random_state=0)
svm1.fit(X_train,y_train)

LinearSVC(random_state=0)

In [533]:
svm1.coef_

array([[-2.30557782,  2.87136628, -1.20251867, -0.04226328, -2.6195562 ,
        -0.        ,  1.09229715,  2.53142646, -0.25718109,  0.88190789,
        -1.54483213,  0.97711229, -5.15250239, -0.05836523, -0.07016647,
        -0.68150931, -4.47405014]])

In [534]:
svm1.intercept_

array([3.98125752])

In [535]:
print('svm acc on train: {:.2%}'.format(svm1.score(X_train, y_train)))
print('svm acc on test: {:.2%}'.format(svm1.score(X_test, y_test)))

svm acc on train: 82.56%
svm acc on test: 81.50%


In [536]:
b=[[0.616,0.999,0.781,0.00001,0.4719,0.0005,0.6306,0.3696,0.0415,0.0022,0.2770,0.9532,0,1.1,0.7021,0.0029,0.0345]]

In [537]:
b_trns=scaler1.transform(b)
b_trns

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[ 0.77180473,  0.97523232,  0.9003833 , -0.        ,  0.46878615,
         0.        ,  0.28705302,  0.3696    ,  0.08202934,  0.        ,
         0.14518228,  0.        , -2.69984748,  0.        ,  0.68655891,
         0.        ,  0.0325461 ]])

In [538]:
svm1.predict(b_trns)

array([1])

In [539]:
svm1.intercept_.round(2)

array([3.98])

In [540]:
svm1.coef_.round(2)

array([[-2.31,  2.87, -1.2 , -0.04, -2.62, -0.  ,  1.09,  2.53, -0.26,
         0.88, -1.54,  0.98, -5.15, -0.06, -0.07, -0.68, -4.47]])

## controlling the complexity of svm by change parameter 'C'

In [541]:
LinearSVC()

LinearSVC()

In [542]:
C_range=[.1,1,5,10,50,100]

In [543]:
train_scores_SVM, test_scores_SVM=validation_curve(LinearSVC(random_state=0, max_iter=100000), X_bank_trns, y_bank, param_name='C',
                                           param_range=[.1,1,5,10,50,100], cv=4)

In [544]:
train_scores_SVM.round(4)

array([[0.7927, 0.7913, 0.7793, 0.8073],
       [0.8227, 0.8173, 0.816 , 0.8253],
       [0.8313, 0.826 , 0.8193, 0.8353],
       [0.8293, 0.8267, 0.8233, 0.8387],
       [0.832 , 0.828 , 0.8267, 0.8373],
       [0.8287, 0.826 , 0.8267, 0.838 ]])

In [545]:
print('ave cross in 4 folds for different C values:')
print('training:', train_scores_SVM.mean(axis=1).round(4))
print('test', test_scores_SVM.mean(axis=1).round(4))

ave cross in 4 folds for different C values:
training: [0.7927 0.8203 0.828  0.8295 0.831  0.8298]
test [0.792  0.819  0.825  0.823  0.8255 0.826 ]


In [546]:
train_scores_SVM.mean()

0.8218888888888888

# Decision tree

In [547]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel, y_bank, test_size=0.2, random_state=0)

In [548]:
X_train

Realized Sales Gross Margin   Operating Profit Rate  \
2976                      0.597580                0.998975   
1752                      0.594027                0.998887   
2545                      0.614321                0.998996   
2043                      0.599281                0.998506   
2195                      0.598589                0.998907   
...                            ...                     ...   
4375                      0.597789                0.998966   
283                       0.607028                0.999047   
2001                      0.540776                0.997789   
5398                      0.606113                0.999038   
1166                      0.590943                0.998589   

       Continuous interest rate (after tax)   Operating Expense Rate  \
2976                               0.781352             5.720000e+09   
1752                               0.781314             8.930000e+09   
2545                               0.781608             3.055116e-04   
2043                               0.778385             5.547083e-04   
2195                               0.781569             1.418860e-04   
...                                     ...                      ...   
4375                               0.781567             7.040000e+09   
283                                0.781640             1.377231e-04   
2001                               0.780105             3.329175e-04   
5398                               0.781624             1.319412e-04   
1166                               0.780786             3.378898e-04   

       Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
2976         0.462057                0.000375                 0.626627   
1752         0.464620                0.000445                 0.630170   
2545         0.470038                0.000492                 0.630665   
2043         0.460156                0.000388                 0.629517   
2195         0.463354                0.000445                 0.634437   
...               ...                     ...                      ...   
4375         0.454421                0.000444                 0.632047   
283          0.460396                0.000464                 0.631275   
2001         0.461074                0.000167                 0.630547   
5398         0.469084                0.000458                 0.630800   
1166         0.461595                0.000395                 0.629981   

       Borrowing dependency   Net Worth Turnover Rate (times)  \
2976               0.384970                          0.020323   
1752               0.378416                          0.045323   
2545               0.369637                          0.123226   
2043               0.380517                          0.010484   
2195               0.371937                          0.020484   
...                     ...                               ...   
4375               0.376490                          0.044677   
283                0.374160                          0.035645   
2001               0.279725                          0.017903   
5398               0.370886                          0.031774   
1166               0.376086                          0.015161   

       Allocation rate per person   Inventory/Working Capital  \
2976                     0.078628                    0.276517   
1752                     0.011180                    0.276787   
2545                     0.005275                    0.272881   
2043                     0.214833                    0.278116   
2195                     0.007471                    0.277510   
...                           ...                         ...   
4375                     0.023803                    0.276581   
283                      0.006648                    0.277619   
2001                     0.042332                    0.276956   
5398                     0.010267                    0.277113   
1166        

In [549]:
train_scores_decision_tree, test_scores_decision_tree=validation_curve(DecisionTreeClassifier(random_state=0), X_train, y_train, param_name='max_leaf_nodes', 
                                          param_range=[2,6,8,10,15,25,50], cv=5)

In [550]:
dt0=DecisionTreeClassifier(random_state=0, max_leaf_nodes=10)
dt0.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [551]:
print('dt0 acc on train: {:.2%}'.format(dt0.score(X_train, y_train)))
print('dt0 acc on test: {:.2%}'.format(dt0.score(X_test, y_test)))

dt0 acc on train: 90.25%
dt0 acc on test: 89.50%


In [552]:
p1=[0.616,0.999,0.781,0.0001,0.471,0.0005,0.631,0.3696,0.0415,0.0022,0.27698,0,0.953,0,0.7022,0.0029,0.0345]
dt0.predict([p1])

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

## visulalzing our decision tree

In [553]:
export_graphviz(dt0, out_file='dt0_vis.dot', feature_names=X_bank_sel.columns, class_names=dt0.classes_.astype(str), impurity=False, filled=True)

In [554]:
dt0.classes_

array([0, 1])

## Feature Importance 

In [555]:
dt0.feature_importances_.round(3)

array([0.033, 0.   , 0.601, 0.   , 0.   , 0.053, 0.029, 0.141, 0.022,
       0.019, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.103])

In [556]:
X_bank_sel.columns

Index([' Realized Sales Gross Margin', ' Operating Profit Rate',
       ' Continuous interest rate (after tax)', ' Operating Expense Rate',
       ' Cash flow rate', ' Net Value Growth Rate', ' Interest Expense Ratio',
       ' Borrowing dependency', ' Net Worth Turnover Rate (times)',
       ' Allocation rate per person', ' Inventory/Working Capital',
       ' Inventory/Current Liability', ' Retained Earnings to Total Assets',
       ' Cash Turnover Rate', ' Current Liability to Liability',
       ' Total assets to GNP price', ' Equity to Liability'],
      dtype='object')

In [557]:
feat_imp=pd.DataFrame(data=dt0.feature_importances_.round(3),index=X_bank_sel.columns, columns=['importance'])
feat_imp.sort_values('importance', ascending=False)

importance
 Continuous interest rate (after tax)       0.601
 Borrowing dependency                       0.141
 Equity to Liability                        0.103
 Net Value Growth Rate                      0.053
 Realized Sales Gross Margin                0.033
 Interest Expense Ratio                     0.029
 Net Worth Turnover Rate (times)            0.022
 Allocation rate per person                 0.019
 Cash flow rate                             0.000
 Operating Expense Rate                     0.000
 Operating Profit Rate                      0.000
 Inventory/Working Capital                  0.000
 Inventory/Current Liability                0.000
 Retained Earnings to Total Assets          0.000
 Cash Turnover Rate                         0.000
 Current Liability to Liability             0.000
 Total assets to GNP price                  0.000

# Random Forest

In [558]:
bank_rf=RandomForestClassifier(n_estimators=300, random_state=0)
bank_rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, random_state=0)

In [559]:
print('bank_rf on train: {:.2%}'.format(bank_rf.score(X_train, y_train)))
print('bank_rf on test: {:.2%}'.format(bank_rf.score(X_test, y_test)))

bank_rf on train: 100.00%
bank_rf on test: 96.50%


## Feature Importance

In [560]:
bank_rf.feature_importances_

array([0.03148619, 0.0427782 , 0.15396602, 0.01972965, 0.03710007,
       0.08806228, 0.08931111, 0.13006438, 0.02368479, 0.02624712,
       0.03605618, 0.02256591, 0.13319418, 0.02562697, 0.01899411,
       0.02206478, 0.09906807])

In [561]:
bank_rf_feat_imp=pd.DataFrame(data=bank_rf.feature_importances_, index=X_bank_sel.columns, columns=['importance'])
bank_rf_feat_imp.sort_values(by=['importance'], ascending=False).round(3)

importance
 Continuous interest rate (after tax)       0.154
 Retained Earnings to Total Assets          0.133
 Borrowing dependency                       0.130
 Equity to Liability                        0.099
 Interest Expense Ratio                     0.089
 Net Value Growth Rate                      0.088
 Operating Profit Rate                      0.043
 Cash flow rate                             0.037
 Inventory/Working Capital                  0.036
 Realized Sales Gross Margin                0.031
 Allocation rate per person                 0.026
 Cash Turnover Rate                         0.026
 Net Worth Turnover Rate (times)            0.024
 Inventory/Current Liability                0.023
 Total assets to GNP price                  0.022
 Operating Expense Rate                     0.020
 Current Liability to Liability             0.019

In [562]:
X_test.iloc[20:25,:]

Realized Sales Gross Margin   Operating Profit Rate  \
4927                      0.601385                0.999041   
2521                      0.590899                0.998823   
4558                      0.609197                0.998994   
2097                      0.610415                0.999087   
2106                      0.589753                0.998878   

       Continuous interest rate (after tax)   Operating Expense Rate  \
4927                               0.781624             5.270000e+09   
2521                               0.781377             1.023383e-04   
4558                               0.781597             2.254912e-04   
2097                               0.781565             1.511369e-04   
2106                               0.781440             2.890000e+09   

       Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
4927         0.475860                0.000443                 0.631241   
2521         0.464033                0.000439                 0.629082   
4558         0.459727                0.000445                 0.631715   
2097         0.455337                0.000387                 0.617487   
2106         0.463349                0.000426                 0.623443   

       Borrowing dependency   Net Worth Turnover Rate (times)  \
4927               0.375087                          0.032258   
2521               0.382352                          0.026935   
4558               0.378647                          0.035161   
2097               0.384455                          0.031290   
2106               0.383173                          0.022419   

       Allocation rate per person   Inventory/Working Capital  \
4927                     0.084615                    0.276399   
2521                     0.043610                    0.276975   
4558                     0.007099                    0.277194   
2097                     0.034323                    0.278546   
2106                     0.036607                    0.278094   

       Inventory/Current Liability   Retained Earnings to Total Assets  \
4927                      0.002225                            0.946754   
2521                      0.000000                            0.919474   
4558                      0.008129                            0.933973   
2097                      0.017323                            0.929100   
2106                      0.012328                            0.928465   

       Cash Turnover Rate   Current Liability to Liability  \
4927         1.310857e-04                         0.579829   
2521         1.826919e-04                         0.511457   
4558         1.262433e-04                         0.487845   
2097         9.460000e+09                         0.990644   
2106         1.782309e-04                         0.813712   

       Total assets to GNP price   Equity to Liability  
4927                    0.483133              0.027919  
2521                    0.010901              0.019908  
4558                    0.001067              0.021673  
2097                    0.005779              0.017979  
2106                    0.053764              0.017870

In [563]:
bank_rf.predict(X_test.iloc[20:25,:])

array([0, 0, 0, 1, 1])

# KNN Classifier

In [564]:
train_scores_KNN, test_scores_KNN=validation_curve(KNeighborsClassifier(), X_bank_trns, y_bank, param_name='n_neighbors', 
                                           param_range=[1,2,3,4,5,6], cv=4)

In [565]:
train_scores_KNN.mean(axis=1)

array([1.        , 0.99066667, 0.941     , 0.92316667, 0.89266667,
       0.877     ])

In [566]:
train_scores_KNN.mean()

0.9374166666666667

In [567]:
test_scores_KNN.mean()

0.8668333333333335

In [568]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel,y_bank,
                                                  random_state=0)

In [569]:
knn_cls_bank_bal=KNeighborsClassifier(n_neighbors=1)

In [570]:
knn_cls_bank_bal.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [571]:
print('knn_cls_bank_bal acc on train: {:.2%}'.format(knn_cls_bank_bal.score(X_train,y_train)))
print('knn_cls_bank_bal acc on test: {:.2%}'.format(knn_cls_bank_bal.score(X_test,y_test)),'\n')

knn_cls_bank_bal acc on train: 97.73%
knn_cls_bank_bal acc on test: 87.40% 



In [572]:
knn_cls_bank_bal.score(X_bank_sel,y_bank)

0.9515

In [573]:
w1=[1,1,0.5,0.4,0.3,0.3,0.6,0.7,1,0.4,0.2,0.5,0.7,0.4,0.1,0.9,0.6]
knn_cls_bank_bal.predict([w1])

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])

In [574]:
knn_cls_bank_bal.predict(X_bank_sel)

array([0, 1, 1, ..., 1, 0, 0])

In [575]:
len(knn_cls_bank_bal.predict(X_bank_sel))

2000

In [576]:
predict_array = knn_cls_bank_bal.predict(X_bank_sel)
count_non_zero = 0
for i in predict_array:
    if i != 1:
        count_non_zero += 1
print(count_non_zero)      

941


In [577]:
sum(knn_cls_bank_bal.predict(X_bank_sel))

1059

In [578]:
X_bank_sel.describe()

Realized Sales Gross Margin   Operating Profit Rate  \
count                   2000.000000             2000.000000   
mean                       0.603785                0.998843   
std                        0.014686                0.000993   
min                        0.449761                0.973424   
25%                        0.597580                0.998857   
50%                        0.602099                0.998976   
75%                        0.609738                0.999044   
max                        0.665151                0.999650   

        Continuous interest rate (after tax)   Operating Expense Rate  \
count                            2000.000000             2.000000e+03   
mean                                0.781041             1.844045e+09   
std                                 0.003344             3.190004e+09   
min                                 0.735093             1.000256e-04   
25%                                 0.781286             1.549529e-04   
50%                                 0.781541             2.864894e-04   
75%                                 0.781652             3.202500e+09   
max                                 0.786079             9.980000e+09   

        Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
count      2000.000000            2.000000e+03              2000.000000   
mean          0.464422            3.732000e+07                 0.631498   
std           0.012146            5.890469e+08                 0.014577   
min           0.343818            0.000000e+00                 0.525126   
25%           0.459606            3.896315e-04                 0.630095   
50%           0.462599            4.406694e-04                 0.630612   
75%           0.466664            4.735780e-04                 0.631087   
max           0.617039            9.330000e+09                 0.892562   

        Borrowing dependency   Net Worth Turnover Rate (times)  \
count            2000.000000                       2000.000000   
mean                0.382959                          0.039831   
std                 0.052685                          0.036178   
min                 0.000000                          0.009032   
25%                 0.371918                          0.021935   
50%                 0.376805                          0.029839   
75%                 0.383465                          0.043750   
max                 1.000000                          0.404839   

        Allocation rate per person   Inventory/Working Capital  \
count                 2.000000e+03                 2000.000000   
mean                  3.480000e+06                    0.277368   
std                   1.100197e+08                    0.005311   
min                   0.000000e+00                    0.244753   
25%                   4.761171e-03                    0.276920   
50%                   1.027135e-02                    0.277135   
75%                   2.309766e-02                    0.277511   
max                   3.480000e+09                    0.466868   

        Inventory/Current Liability   Retained Earnings to Total Assets  \
count                  2.000000e+03                         2000.000000   
mean                   3.585150e+07                            0.919430   
std                    4.840476e+08                            0.034846   
min                    0.000000e+00                            0.728885   
25%                    2.487101e-03                            0.909662   
50%                    5.344259e-03                            0.930045   
75%                    9.879049e-03                            0.938763   
max                    9.910000e+09                            0.998858   

        Cash Turnover Rate   Current Liability to Liability  \
count         2.000000e+03                      2000.000000   
mean          2.332955e+09                         0.748211   
std           2.687308e+09                         