In [28]:
import pandas as pd
import numpy as np

In [29]:
blood = pd.read_csv('blood_donation.csv')
blood.fillna(value=blood.mean(),inplace=True)
blood.head(2)

/var/folders/yl/7fz36w6555x8lddq1hvcnv0r0000gn/T/ipykernel_9861/4149889676.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  blood.fillna(value=blood.mean(),inplace=True)


Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [30]:
x_default, y_default = blood.iloc[:,:-1],blood['Donated2020']
display(x_default.head(1))
display(y_default.head(1))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98

0    1
Name: Donated2020, dtype: int64

In [31]:
x_dummies=pd.get_dummies(x_default)
x_dummies

Age  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.000000        2         50          12500                     98   
1    27.000000        1         13           3250                     28   
2    34.000000        1         16           4000                     35   
3    44.011765        2         20           5000                     45   
4    47.000000        1         24           6000                     77   
..         ...      ...        ...            ...                    ...   
856  33.000000        7          9           2350                     45   
857  34.000000        2         10           2450                     45   
858  28.000000       10          8           1700                     24   
859  21.000000        8          7           1550                     42   
860  38.000000        6          8           2000                     11   

     Gender_Female  Gender_Male  Gender_Other  
0                0            1             0  
1                0            1             0  
2                0            0             1  
3                1            0             0  
4                0            1             0  
..             ...          ...           ...  
856              0            1             0  
857              1            0             0  
858              0            1             0  
859              1            0             0  
860              1            0             0  

[861 rows x 8 columns]

In [32]:
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x_dummies,y_default,random_state=0)

In [34]:
x_train.describe()

Age     Recency   Frequency  TotalDonation  \
count  645.000000  645.000000  645.000000     645.000000   
mean    44.096306    8.631008    5.663566    1414.806202   
std     10.452348    6.863824    5.453074    1361.208988   
min     16.000000    1.000000    1.000000     250.000000   
25%     39.000000    2.000000    2.000000     500.000000   
50%     45.000000    6.000000    5.000000    1150.000000   
75%     52.000000   14.000000    7.000000    1750.000000   
max     60.000000   40.000000   50.000000   12500.000000   

       TimeFromFirstDonation  Gender_Female  Gender_Male  Gender_Other  
count             645.000000     645.000000   645.000000    645.000000  
mean               33.620155       0.493023     0.493023      0.013953  
std                23.375876       0.500339     0.500339      0.117389  
min                 2.000000       0.000000     0.000000      0.000000  
25%                16.000000       0.000000     0.000000      0.000000  
50%                28.000000       0.000000     0.000000      0.000000  
75%                46.000000       1.000000     1.000000      0.000000  
max                98.000000       1.000000     1.000000      1.000000

In [35]:
from sklearn.linear_model import LogisticRegression

In [65]:
LogisticRegression(solver='lbfgs' , max_iter=1000 , C=0.1)

LogisticRegression(C=0.1, max_iter=1000)

In [66]:
log_reg.fit(x_train, y_train)

LogisticRegression(C=0.1, max_iter=1000)

In [67]:
log_reg.coef_.round(2)

array([[-0.53, -0.09, -0.03,  0.  , -0.02,  0.13, -0.07, -0.07]])

In [68]:
print('log reg acc on train: {:.2%}'.format(log_reg.score(x_train,y_train)))
print('log reg acc on test: {:.2%}'.format(log_reg.score(x_test,y_test)))

log reg acc on train: 91.78%
log reg acc on test: 91.20%


In [70]:
b = [41, 7, 5, 1150, 27, 0, 1, 0]
log_reg.predict([b])

/Users/ryanmaki/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [76]:
#Age=39,     Gender="Female",      Recency=7,     Frequency=5,    TotalDonation=1150,    TimeFromFirstDonation=27
b1 = [39, 7, 5, 1150, 27, 0, 1, 0]
log_reg.predict_proba([b1])
#log_reg.predict([b1])

/Users/ryanmaki/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.28988226, 0.71011774]])

In [42]:
log_reg.classes_

array([0, 1])

In [43]:
knn1=KNeighborsClassifier(n_neighbors=1)

In [44]:
knn1.fit(x_train,y_train)
knn1.fit(x_train,y_train)
knn1.fit(x_train,y_train)
knn1.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [45]:
print('knn1 accruacy on train: {:.2%}'.format(knn1.score(x_train,y_train)))
print('knn1 accruacy on test: {:.2%}'.format(knn1.score(x_test,y_test)),'\n')

knn1 accruacy on train: 99.53%
knn1 accruacy on test: 84.72% 



In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
scaler1=MinMaxScaler()
x_dummies_transformed=scaler1.fit_transform(x_dummies)
x_dummies_transformed

array([[0.59090909, 0.01369863, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.25      , 0.        , 0.24489796, ..., 0.        , 1.        ,
        0.        ],
       [0.40909091, 0.        , 0.30612245, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.27272727, 0.12328767, 0.14285714, ..., 0.        , 1.        ,
        0.        ],
       [0.11363636, 0.09589041, 0.12244898, ..., 1.        , 0.        ,
        0.        ],
       [0.5       , 0.06849315, 0.14285714, ..., 1.        , 0.        ,
        0.        ]])

In [48]:
from sklearn.model_selection import validation_curve

In [55]:
from sklearn.linear_model import LogisticRegression

C_range=[.1,.5,1,10,100,200]
train_scores, test_scores = validation_curve(LogisticRegression(max_iter=10000),x_dummies_transformed,y_default,param_name='C',
                                            param_range=C_range,cv=4)
train_scores.round(4)

array([[0.8822, 0.8684, 0.8514, 0.8406],
       [0.9395, 0.9381, 0.918 , 0.8947],
       [0.9411, 0.935 , 0.9241, 0.904 ],
       [0.9333, 0.935 , 0.9211, 0.8947],
       [0.9302, 0.935 , 0.9149, 0.8932],
       [0.9287, 0.935 , 0.9149, 0.8932]])

In [56]:
test_scores.round(4)

array([[0.8102, 0.8186, 0.8558, 0.9256],
       [0.875 , 0.8651, 0.9395, 1.    ],
       [0.8889, 0.8791, 0.9349, 1.    ],
       [0.875 , 0.8884, 0.9302, 0.9953],
       [0.8611, 0.8884, 0.9209, 0.9907],
       [0.8611, 0.8837, 0.9163, 0.9907]])

In [61]:
test_scores.mean()

0.9081063379270744

In [ ]:
Age=41,     Gender="Female",      Recency=7,     Frequency=5,    TotalDonation=1150,    TimeFromFirstDonation=27

In [64]:
LogisticRegression.predict(b)

TypeError: predict() missing 1 required positional argument: 'X'

In [51]:
s1="Data analysis is a process of inspecting, cleansing, transforming, and modeling data with the goal of discovering useful information, informing conclusions, and supporting decision-making. Data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. In today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more effectively. Data mining is a particular data analysis technique that focuses on statistical modeling and knowledge discovery for predictive rather than purely descriptive purposes, while business intelligence covers data analysis that relies heavily on aggregation, focusing mainly on business information. In statistical applications, data analysis can be divided into descriptive statistics, exploratory data analysis (EDA), and confirmatory data analysis (CDA). EDA focuses on discovering new features in the data while CDA focuses on confirming or falsifying existing hypotheses. The Predictive analytics focuses on the application of statistical models for predictive forecasting or classification, while text analytics applies statistical, linguistic, and structural techniques to extract and classify information from textual sources, a species of unstructured data. All of the above are varieties of data analysis. Once processed and organized, the data may be incomplete, contain duplicates, or contain errors. The need for data cleaning, will arise from problems in the way that the datum are entered and stored. Data cleaning is the process of preventing and correcting these errors. And, Common tasks include record matching, identifying inaccuracy of data, overall quality of existing data, deduplication, and column segmentation.[7] Such data problems can also be identified through a variety of analytical techniques. For example, with financial information, the totals for particular variables may be compared against separately published numbers, that are believed to be reliable. Of Unusual amounts, above or below predetermined thresholds, may also be reviewed. There are several types of data cleaning, that are dependent upon the type of data in the set; this could be phone numbers, email addresses, employers, or other values. Quantitative data methods for outlier detection, can be used to get rid of data that appears to have a higher likelihood of being input incorrectly. Of Textual data spell checkers, can be used to lessen the amount of mistyped words, however, it is harder to tell if the words themselves are correct."

In [52]:
s1.count('and')

14

In [53]:
a1="45 , 11 , 43 , 20"

In [54]:
a1.argmin()

AttributeError: 'str' object has no attribute 'argmin'

In [41]:
a3=[[23, 65, 2], 'Hi', True, False, 'Python']
a3[1:3]

['Hi', True]

In [42]:
import numpy as np
a1=np.array([11,3,0,33,20])
a1.argmax()

3

In [43]:
x_default.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

In [1]:
a1=234

a2=False

a3='4500'

a4=254.32

In [7]:
type(a4)

float

In [9]:
s1 = s1="Data analysis is a process of inspecting, cleansing, transforming, and modeling data with the goal of discovering useful information, informing conclusions, and supporting decision-making. Data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. In today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more effectively. Data mining is a particular data analysis technique that focuses on statistical modeling and knowledge discovery for predictive rather than purely descriptive purposes, while business intelligence covers data analysis that relies heavily on aggregation, focusing mainly on business information. In statistical applications, data analysis can be divided into descriptive statistics, exploratory data analysis (EDA), and confirmatory data analysis (CDA). EDA focuses on discovering new features in the data while CDA focuses on confirming or falsifying existing hypotheses. The Predictive analytics focuses on the application of statistical models for predictive forecasting or classification, while text analytics applies statistical, linguistic, and structural techniques to extract and classify information from textual sources, a species of unstructured data. All of the above are varieties of data analysis. Once processed and organized, the data may be incomplete, contain duplicates, or contain errors. The need for data cleaning, will arise from problems in the way that the datum are entered and stored. Data cleaning is the process of preventing and correcting these errors. And, Common tasks include record matching, identifying inaccuracy of data, overall quality of existing data, deduplication, and column segmentation.[7] Such data problems can also be identified through a variety of analytical techniques. For example, with financial information, the totals for particular variables may be compared against separately published numbers, that are believed to be reliable. Of Unusual amounts, above or below predetermined thresholds, may also be reviewed. There are several types of data cleaning, that are dependent upon the type of data in the set; this could be phone numbers, email addresses, employers, or other values. Quantitative data methods for outlier detection, can be used to get rid of data that appears to have a higher likelihood of being input incorrectly. Of Textual data spell checkers, can be used to lessen the amount of mistyped words, however, it is harder to tell if the words themselves are correct."

In [11]:
s1.count('of')

16

In [12]:
a1="45 , 11 , 43 , 20"

In [18]:
a1.count('45')

1

In [17]:
a1.remove('45')

AttributeError: 'str' object has no attribute 'remove'

In [15]:
a1.argmin()

AttributeError: 'str' object has no attribute 'argmin'

In [19]:
a3=[[23, 65, 2], 'Hi', True, False, 'Python']

In [20]:

a3[1:3]

['Hi', True]

In [25]:
a1=np.array([11,3,0,33,20])

In [26]:
a1.argmax()

3