In [1]:
import pandas as pd

In [5]:
bd=pd.read_csv('blood_donation.csv')
bd

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

# Week 3 Class 4

In [12]:
bd.head()

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
1  27.0    Male        1         13           3250                     28   
2  34.0   Other        1         16           4000                     35   
3   NaN  Female        2         20           5000                     45   
4  47.0    Male        1         24           6000                     77   

   Donated2020  
0            1  
1            1  
2            1  
3            1  
4            0

In [14]:
bd.tail()

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
856            1  
857            1  
858            1  
859            1  
860            1

In [16]:
bd.tail(7)

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
854  26.0    Male        8          7           1950                     13   
855  21.0  Female        5          8           1650                     38   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
854            1  
855            1  
856            1  
857            1  
858            1  
859            1  
860            1

## infor about the dataset

In [17]:
bd.shape

(861, 7)

In [18]:
bd.dtypes

Age                      float64
Gender                    object
Recency                    int64
Frequency                  int64
TotalDonation              int64
TimeFromFirstDonation      int64
Donated2020                int64
dtype: object

In [19]:
bd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Age                    850 non-null    float64
 1   Gender                 861 non-null    object 
 2   Recency                861 non-null    int64  
 3   Frequency              861 non-null    int64  
 4   TotalDonation          861 non-null    int64  
 5   TimeFromFirstDonation  861 non-null    int64  
 6   Donated2020            861 non-null    int64  
dtypes: float64(1), int64(5), object(1)
memory usage: 47.2+ KB


In [20]:
pd.reset_option('^display')
bd

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

## DataFrame Components 

In [21]:
bd.columns

Index(['Age', 'Gender', 'Recency', 'Frequency', 'TotalDonation',
       'TimeFromFirstDonation', 'Donated2020'],
      dtype='object')

In [22]:
bd.index

RangeIndex(start=0, stop=861, step=1)

In [23]:
bd.values

array([[42.0, 'Male', 2, ..., 12500, 98, 1],
       [27.0, 'Male', 1, ..., 3250, 28, 1],
       [34.0, 'Other', 1, ..., 4000, 35, 1],
       ...,
       [28.0, 'Male', 10, ..., 1700, 24, 1],
       [21.0, 'Female', 8, ..., 1550, 42, 1],
       [38.0, 'Female', 6, ..., 2000, 11, 1]], dtype=object)

## Sorting DataFrame

In [26]:
bd.sort_values(by=['Gender'])

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
860  38.0  Female        6          8           2000                     11   
353  48.0  Female       11          2            500                     21   
352  41.0  Female       11          5           1250                     50   
676  49.0  Female       14          3            750                     26   
350  57.0  Female       11          1            250                     11   
..    ...     ...      ...        ...            ...                    ...   
521  32.0   Other        2         11           2750                     41   
92   47.0   Other        4          2            500                      4   
21   46.0   Other        4         11           2750                     28   
62   50.0   Other        2         10           2500                     49   
105  55.0   Other        6         17           4250                     70   

     Donated2020  
860            1  
353            0  
352            0  
676            0  
350            0  
..           ...  
521            1  
92             0  
21             0  
62             0  
105            0  

[861 rows x 7 columns]

In [28]:
bd.sort_values(by=['Age'])

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
763  16.0  Female        7          7           1600                     46   
797  17.0    Male        7          7           1500                     43   
793  17.0    Male        4          6           1650                     47   
822  17.0  Female        8          5           1300                     36   
821  17.0    Male        1          6           1550                     50   
..    ...     ...      ...        ...            ...                    ...   
78    NaN   Other        2          2            500                      4   
102   NaN    Male        4          9           2250                     40   
136   NaN    Male        2          5           1250                     37   
191   NaN    Male        4          7           1750                     52   
203   NaN  Female        4          7           1750                     58   

     Donated2020  
763            1  
797            1  
793            1  
822            1  
821            1  
..           ...  
78             0  
102            0  
136            0  
191            0  
203            0  

[861 rows x 7 columns]

In [30]:
bd.sort_values(by=['Age', 'Gender'])

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
763  16.0  Female        7          7           1600                     46   
795  17.0  Female        8          3           1000                     33   
822  17.0  Female        8          5           1300                     36   
782  17.0    Male        3          9           1900                     34   
793  17.0    Male        4          6           1650                     47   
..    ...     ...      ...        ...            ...                    ...   
102   NaN    Male        4          9           2250                     40   
136   NaN    Male        2          5           1250                     37   
191   NaN    Male        4          7           1750                     52   
53    NaN   Other        2         12           3000                     52   
78    NaN   Other        2          2            500                      4   

     Donated2020  
763            1  
795            1  
822            1  
782            1  
793            1  
..           ...  
102            0  
136            0  
191            0  
53             0  
78             0  

[861 rows x 7 columns]

In [32]:
# descending (large to small) ascending=False. ascending (Small to Large), ascending=True. 
bd.sort_values(by=['Frequency'],ascending=False)

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
9    44.0    Male        5         46          11500                     98   
503  60.0  Female        2         44          11000                     98   
500  32.0    Male        2         43          10750                     86   
505  35.0  Female        2         41          10250                     98   
..    ...     ...      ...        ...            ...                    ...   
230  51.0    Male        4          1            250                      4   
693  53.0    Male       14          1            250                     14   
692  42.0  Female       14          1            250                     14   
668  43.0    Male       11          1            250                     11   
415  56.0    Male       16          1            250                     16   

     Donated2020  
0              1  
9              1  
503            0  
500            1  
505            1  
..           ...  
230            0  
693            0  
692            0  
668            0  
415            0  

[861 rows x 7 columns]

In [34]:
bd.sort_values(by=['Recency','Frequency'],ascending=False)

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
499  40.0    Male       74          1            250                     74   
747  44.0  Female       72          1            250                     72   
498  59.0  Female       40          1            250                     40   
746  44.0    Male       39          1            250                     39   
496  42.0  Female       38          1            250                     38   
..    ...     ...      ...        ...            ...                    ...   
815  22.0  Female        1          5           1400                     44   
803  36.0  Female        1          4           1050                     36   
811  34.0  Female        1          4           1050                     38   
11   55.0    Male        1          3            750                      4   
67   53.0    Male        1          2            500                      4   

     Donated2020  
499            0  
747            0  
498            0  
746            0  
496            0  
..           ...  
815            1  
803            1  
811            1  
11             0  
67             0  

[861 rows x 7 columns]

In [38]:
bd.sort_values(by=['Recency','Frequency'],
               ascending=[False,False])

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
499  40.0    Male       74          1            250                     74   
747  44.0  Female       72          1            250                     72   
498  59.0  Female       40          1            250                     40   
746  44.0    Male       39          1            250                     39   
496  42.0  Female       38          1            250                     38   
..    ...     ...      ...        ...            ...                    ...   
815  22.0  Female        1          5           1400                     44   
803  36.0  Female        1          4           1050                     36   
811  34.0  Female        1          4           1050                     38   
11   55.0    Male        1          3            750                      4   
67   53.0    Male        1          2            500                      4   

     Donated2020  
499            0  
747            0  
498            0  
746            0  
496            0  
..           ...  
815            1  
803            1  
811            1  
11             0  
67             0  

[861 rows x 7 columns]

In [39]:
bd.loc[800,'TotalDonation']

2100

In [40]:
bd.describe()

Age     Recency   Frequency  TotalDonation  \
count  850.000000  861.000000  861.000000     861.000000   
mean    44.011765    9.047619    5.695703    1420.905923   
std     10.549557    7.707822    5.510062    1374.249771   
min     16.000000    1.000000    1.000000     250.000000   
25%     38.000000    3.000000    2.000000     500.000000   
50%     45.000000    7.000000    4.000000    1150.000000   
75%     52.000000   14.000000    7.000000    1850.000000   
max     60.000000   74.000000   50.000000   12500.000000   

       TimeFromFirstDonation  Donated2020  
count             861.000000   861.000000  
mean               33.771196     0.337979  
std                23.144187     0.473296  
min                 2.000000     0.000000  
25%                16.000000     0.000000  
50%                28.000000     0.000000  
75%                46.000000     1.000000  
max                98.000000     1.000000

In [41]:
bd.sort_values(by=['TotalDonation'],inplace=True)

In [42]:
bd.sort_index(inplace=True)
bd

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

## Subsetting DataFrame

In [45]:
bd[['Recency','Frequency','TimeFromFirstDonation']]

Recency  Frequency  TimeFromFirstDonation
0          2         50                     98
1          1         13                     28
2          1         16                     35
3          2         20                     45
4          1         24                     77
..       ...        ...                    ...
856        7          9                     45
857        2         10                     45
858       10          8                     24
859        8          7                     42
860        6          8                     11

[861 rows x 3 columns]

In [46]:
bd[['Recency']]

Recency
0          2
1          1
2          1
3          2
4          1
..       ...
856        7
857        2
858       10
859        8
860        6

[861 rows x 1 columns]

In [48]:
bd['Recency']

0       2
1       1
2       1
3       2
4       1
       ..
856     7
857     2
858    10
859     8
860     6
Name: Recency, Length: 861, dtype: int64

In [51]:
bd[['Recency', 'Frequency']]

Recency  Frequency
0          2         50
1          1         13
2          1         16
3          2         20
4          1         24
..       ...        ...
856        7          9
857        2         10
858       10          8
859        8          7
860        6          8

[861 rows x 2 columns]

# Week3 Class 5

## iloc (only rows)

In [53]:
bd.iloc[20]

Age                      41.0
Gender                   Male
Recency                     2
Frequency                   3
TotalDonation             750
TimeFromFirstDonation       4
Donated2020                 1
Name: 20, dtype: object

In [55]:
bd.iloc[[20]]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
20  41.0   Male        2          3            750                      4   

    Donated2020  
20            1

In [56]:
bd.iloc[[49,54,69]]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
49  49.0    Male        2          2            500                      2   
54  26.0  Female        4          5           1250                     14   
69  44.0    Male        1          9           2250                     51   

    Donated2020  
49            0  
54            1  
69            0

In [58]:
bd.iloc[39:60]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
39  38.0    Male        4          7           1750                     22   
40  28.0  Female        2         13           3250                     53   
41  45.0   Other        2          5           1250                     16   
42  37.0    Male        2          5           1250                     16   
43  60.0    Male        2          5           1250                     16   
44  37.0    Male        4         20           5000                     69   
45  34.0    Male        4          9           2250                     28   
46  54.0    Male        2          9           2250                     36   
47  44.0    Male        2          2            500                      2   
48  41.0    Male        2          2            500                      2   
49  49.0    Male        2          2            500                      2   
50  57.0    Male        2         11           2750                     46   
51  41.0  Female        2         11           2750                     46   
52  41.0    Male        2          6           1500                     22   
53   NaN   Other        2         12           3000                     52   
54  26.0  Female        4          5           1250                     14   
55  42.0  Female        4         19           4750                     69   
56  28.0  Female        4          8           2000                     26   
57  36.0    Male        2          7           1750                     28   
58  47.0  Female        2         16           4000                     81   
59  59.0    Male        3          6           1500                     21   

    Donated2020  
39            1  
40            1  
41            0  
42            1  
43            0  
44            1  
45            1  
46            0  
47            0  
48            0  
49            0  
50            0  
51            1  
52            0  
53            0  
54            1  
55            1  
56            1  
57            1  
58            0  
59            0

## iloc

In [61]:
bd.iloc[:,2]

0       2
1       1
2       1
3       2
4       1
       ..
856     7
857     2
858    10
859     8
860     6
Name: Recency, Length: 861, dtype: int64

In [64]:
bd.iloc[:,[2]]

Recency
0          2
1          1
2          1
3          2
4          1
..       ...
856        7
857        2
858       10
859        8
860        6

[861 rows x 1 columns]

In [65]:
bd.iloc[:,[0,4,-1]]

Age  TotalDonation  Donated2020
0    42.0          12500            1
1    27.0           3250            1
2    34.0           4000            1
3     NaN           5000            1
4    47.0           6000            0
..    ...            ...          ...
856  33.0           2350            1
857  34.0           2450            1
858  28.0           1700            1
859  21.0           1550            1
860  38.0           2000            1

[861 rows x 3 columns]

## Both rows and columns

In [67]:
# get the 10th, 50th, and 100th rows and
# first and last cols
bd.iloc[[9,49,99],[0,-1]]

Age  Donated2020
9   44.0            1
49  49.0            0
99  42.0            1

In [75]:
bd.iloc[-20: , :3]

Age  Gender  Recency
841  27.0  Female        8
842  19.0    Male        7
843  37.0    Male        1
844  27.0  Female       10
845  29.0  Female        4
846  31.0  Female        8
847  24.0  Female        5
848  21.0    Male       10
849  35.0    Male        4
850  34.0    Male        7
851  35.0  Female        8
852  22.0  Female       10
853  30.0    Male        7
854  26.0    Male        8
855  21.0  Female        5
856  33.0    Male        7
857  34.0  Female        2
858  28.0    Male       10
859  21.0  Female        8
860  38.0  Female        6

In [76]:
bd.iloc[:25 , [1,-1]]

Gender  Donated2020
0     Male            1
1     Male            1
2    Other            1
3   Female            1
4     Male            0
5     Male            0
6    Other            1
7   Female            0
8   Female            1
9     Male            1
10  Female            0
11    Male            0
12    Male            1
13    Male            0
14  Female            1
15  Female            1
16    Male            1
17    Male            1
18   Other            1
19    Male            1
20    Male            1
21   Other            0
22  Female            1
23    Male            1
24  Female            0

## loc

In [77]:
bd.loc[6]

Age                       41.0
Gender                   Other
Recency                      2
Frequency                    7
TotalDonation             1750
TimeFromFirstDonation       14
Donated2020                  1
Name: 6, dtype: object

In [78]:
bd.loc[[6]]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
6  41.0  Other        2          7           1750                     14   

   Donated2020  
6            1

In [80]:
bd.loc[[25,34,78]]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
25  59.0    Male        4         14           3500                     40   
34  56.0  Female        2         16           4000                     64   
78   NaN   Other        2          2            500                      4   

    Donated2020  
25            0  
34            0  
78            0

In [82]:
bd.loc[:3]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
1  27.0    Male        1         13           3250                     28   
2  34.0   Other        1         16           4000                     35   
3   NaN  Female        2         20           5000                     45   

   Donated2020  
0            1  
1            1  
2            1  
3            1

In [84]:
bd.iloc[:4]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
1  27.0    Male        1         13           3250                     28   
2  34.0   Other        1         16           4000                     35   
3   NaN  Female        2         20           5000                     45   

   Donated2020  
0            1  
1            1  
2            1  
3            1

In [86]:
# subset rows with index 10 to 15-- using both loc and iloc
# loc-- end is inclusive
bd.loc[10:15]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
10  44.0  Female        4         23           5750                     58   
11  55.0    Male        1          3            750                      4   
12   NaN    Male        2         10           2500                     28   
13  41.0    Male        1         13           3250                     47   
14  36.0  Female        2          6           1500                     15   
15  28.0  Female        2          5           1250                     11   

    Donated2020  
10            0  
11            0  
12            1  
13            0  
14            1  
15            1

In [87]:
# subset rows with index 10 to 15-- using both loc and iloc
# iloc-- end is exlusive
bd.iloc[10:16]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
10  44.0  Female        4         23           5750                     58   
11  55.0    Male        1          3            750                      4   
12   NaN    Male        2         10           2500                     28   
13  41.0    Male        1         13           3250                     47   
14  36.0  Female        2          6           1500                     15   
15  28.0  Female        2          5           1250                     11   

    Donated2020  
10            0  
11            0  
12            1  
13            0  
14            1  
15            1

## Only cols

In [88]:
bd.loc[: , ['Gender','Recency','Frequency']]

Gender  Recency  Frequency
0      Male        2         50
1      Male        1         13
2     Other        1         16
3    Female        2         20
4      Male        1         24
..      ...      ...        ...
856    Male        7          9
857  Female        2         10
858    Male       10          8
859  Female        8          7
860  Female        6          8

[861 rows x 3 columns]

In [91]:
bd.loc[: , 'Gender':]

Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0      Male        2         50          12500                     98   
1      Male        1         13           3250                     28   
2     Other        1         16           4000                     35   
3    Female        2         20           5000                     45   
4      Male        1         24           6000                     77   
..      ...      ...        ...            ...                    ...   
856    Male        7          9           2350                     45   
857  Female        2         10           2450                     45   
858    Male       10          8           1700                     24   
859  Female        8          7           1550                     42   
860  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 6 columns]

## both rows and columns 

In [96]:
# subset 5th, 10th, and 13th rows and 'Age' and 'BMI'
bd.loc[[4,9,12] , ['TotalDonation','Frequency']]

TotalDonation  Frequency
4            6000         24
9           11500         46
12           2500         10

In [98]:
# first 4 rows and columns from `Recency` to 'Donated2020'
bd.loc[:3 , 'Recency':'Donated2020']

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Donated2020
0        2         50          12500                     98            1
1        1         13           3250                     28            1
2        1         16           4000                     35            1
3        2         20           5000                     45            1

In [100]:
# rows with index 5, 14, 100 and 
# cols up to (and including) 'Inslulin'
bd.loc[[5,14,100] , :'Frequency']

Age  Gender  Recency  Frequency
5     NaN    Male        4          4
14   36.0  Female        2          6
100  36.0    Male        4          8

In [102]:
# get the BloodPressure for patient w index 532
bd.loc[532,'Frequency']

8

In [103]:
# what is the BMI for the 60th patient in the data?
bd.loc[59,'Recency']

3

In [108]:
# what is the Glucose for the last patient?
# 0 is rows, 1 is columns

bd.shape[0]

861

In [110]:
bd.loc[860,'Recency']

6

In [113]:
bd.iloc[-1,2]

6

In [116]:
bd.iloc[-1,bd.columns.get_loc('Recency')]

6

In [117]:
bd.loc[:,:]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

## renaming 

In [119]:
bd1=bd.iloc[:5].copy()
bd1

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
1  27.0    Male        1         13           3250                     28   
2  34.0   Other        1         16           4000                     35   
3   NaN  Female        2         20           5000                     45   
4  47.0    Male        1         24           6000                     77   

   Donated2020  
0            1  
1            1  
2            1  
3            1  
4            0

In [120]:
bd1.rename(columns={'Gender':'G_d' , 'Frequency':'Fre'},
           index={0:'p1',1:'p2', 2:'p3' , 3:'p4' , 4:'p5'},inplace=True)
bd1

Age     G_d  Recency  Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male        2   50          12500                     98   
p2  27.0    Male        1   13           3250                     28   
p3  34.0   Other        1   16           4000                     35   
p4   NaN  Female        2   20           5000                     45   
p5  47.0    Male        1   24           6000                     77   

    Donated2020  
p1            1  
p2            1  
p3            1  
p4            1  
p5            0

## dropping rows and columns

In [122]:
bd1.drop(['p1','p3'])

Age     G_d  Recency  Fre  TotalDonation  TimeFromFirstDonation  \
p2  27.0    Male        1   13           3250                     28   
p4   NaN  Female        2   20           5000                     45   
p5  47.0    Male        1   24           6000                     77   

    Donated2020  
p2            1  
p4            1  
p5            0

In [123]:
bd1.drop(columns=['Fre'])

Age     G_d  Recency  TotalDonation  TimeFromFirstDonation  Donated2020
p1  42.0    Male        2          12500                     98            1
p2  27.0    Male        1           3250                     28            1
p3  34.0   Other        1           4000                     35            1
p4   NaN  Female        2           5000                     45            1
p5  47.0    Male        1           6000                     77            0

In [124]:
bd1.drop(index=['p1','p2'],columns=['G_d','Fre'])

Age  Recency  TotalDonation  TimeFromFirstDonation  Donated2020
p3  34.0        1           4000                     35            1
p4   NaN        2           5000                     45            1
p5  47.0        1           6000                     77            0

In [126]:
# Adding new columns and rows (new columns)
bd1['new_col1']=5
bd1

Age     G_d  Recency  Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male        2   50          12500                     98   
p2  27.0    Male        1   13           3250                     28   
p3  34.0   Other        1   16           4000                     35   
p4   NaN  Female        2   20           5000                     45   
p5  47.0    Male        1   24           6000                     77   

    Donated2020  new_col1  
p1            1         5  
p2            1         5  
p3            1         5  
p4            1         5  
p5            0         5

In [127]:
bd1['new_col2']=[11,5,6,0,-1]
bd1

Age     G_d  Recency  Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male        2   50          12500                     98   
p2  27.0    Male        1   13           3250                     28   
p3  34.0   Other        1   16           4000                     35   
p4   NaN  Female        2   20           5000                     45   
p5  47.0    Male        1   24           6000                     77   

    Donated2020  new_col1  new_col2  
p1            1         5        11  
p2            1         5         5  
p3            1         5         6  
p4            1         5         0  
p5            0         5        -1

In [128]:
bd1['new_col3']=bd1['new_col1']+bd1['new_col2']
bd1

Age     G_d  Recency  Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male        2   50          12500                     98   
p2  27.0    Male        1   13           3250                     28   
p3  34.0   Other        1   16           4000                     35   
p4   NaN  Female        2   20           5000                     45   
p5  47.0    Male        1   24           6000                     77   

    Donated2020  new_col1  new_col2  new_col3  
p1            1         5        11        16  
p2            1         5         5        10  
p3            1         5         6        11  
p4            1         5         0         5  
p5            0         5        -1         4

## Adding new rows

In [129]:
import numpy as np

In [130]:
bd1.loc['p6']=np.nan
bd1

Age     G_d  Recency   Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male      2.0  50.0        12500.0                   98.0   
p2  27.0    Male      1.0  13.0         3250.0                   28.0   
p3  34.0   Other      1.0  16.0         4000.0                   35.0   
p4   NaN  Female      2.0  20.0         5000.0                   45.0   
p5  47.0    Male      1.0  24.0         6000.0                   77.0   
p6   NaN     NaN      NaN   NaN            NaN                    NaN   

    Donated2020  new_col1  new_col2  new_col3  
p1          1.0       5.0      11.0      16.0  
p2          1.0       5.0       5.0      10.0  
p3          1.0       5.0       6.0      11.0  
p4          1.0       5.0       0.0       5.0  
p5          0.0       5.0      -1.0       4.0  
p6          NaN       NaN       NaN       NaN

In [131]:
bd1.loc['p7']=bd1.loc['p2']
bd1

Age     G_d  Recency   Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male      2.0  50.0        12500.0                   98.0   
p2  27.0    Male      1.0  13.0         3250.0                   28.0   
p3  34.0   Other      1.0  16.0         4000.0                   35.0   
p4   NaN  Female      2.0  20.0         5000.0                   45.0   
p5  47.0    Male      1.0  24.0         6000.0                   77.0   
p6   NaN     NaN      NaN   NaN            NaN                    NaN   
p7  27.0    Male      1.0  13.0         3250.0                   28.0   

    Donated2020  new_col1  new_col2  new_col3  
p1          1.0       5.0      11.0      16.0  
p2          1.0       5.0       5.0      10.0  
p3          1.0       5.0       6.0      11.0  
p4          1.0       5.0       0.0       5.0  
p5          0.0       5.0      -1.0       4.0  
p6          NaN       NaN       NaN       NaN  
p7          1.0       5.0       5.0      10.0

In [132]:
bd1.drop_duplicates()

Age     G_d  Recency   Fre  TotalDonation  TimeFromFirstDonation  \
p1  42.0    Male      2.0  50.0        12500.0                   98.0   
p2  27.0    Male      1.0  13.0         3250.0                   28.0   
p3  34.0   Other      1.0  16.0         4000.0                   35.0   
p4   NaN  Female      2.0  20.0         5000.0                   45.0   
p5  47.0    Male      1.0  24.0         6000.0                   77.0   
p6   NaN     NaN      NaN   NaN            NaN                    NaN   

    Donated2020  new_col1  new_col2  new_col3  
p1          1.0       5.0      11.0      16.0  
p2          1.0       5.0       5.0      10.0  
p3          1.0       5.0       6.0      11.0  
p4          1.0       5.0       0.0       5.0  
p5          0.0       5.0      -1.0       4.0  
p6          NaN       NaN       NaN       NaN

## Descriptive Statistics 

In [134]:
bd.describe()

Age     Recency   Frequency  TotalDonation  \
count  850.000000  861.000000  861.000000     861.000000   
mean    44.011765    9.047619    5.695703    1420.905923   
std     10.549557    7.707822    5.510062    1374.249771   
min     16.000000    1.000000    1.000000     250.000000   
25%     38.000000    3.000000    2.000000     500.000000   
50%     45.000000    7.000000    4.000000    1150.000000   
75%     52.000000   14.000000    7.000000    1850.000000   
max     60.000000   74.000000   50.000000   12500.000000   

       TimeFromFirstDonation  Donated2020  
count             861.000000   861.000000  
mean               33.771196     0.337979  
std                23.144187     0.473296  
min                 2.000000     0.000000  
25%                16.000000     0.000000  
50%                28.000000     0.000000  
75%                46.000000     1.000000  
max                98.000000     1.000000

In [135]:
bd.mean()

Age                        44.011765
Recency                     9.047619
Frequency                   5.695703
TotalDonation            1420.905923
TimeFromFirstDonation      33.771196
Donated2020                 0.337979
dtype: float64

# Week 4  Monday Class 6

In [193]:
bd=pd.read_csv('blood_donation.csv')
bd

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

In [194]:
bd2=bd2.iloc[:7].copy()
bd2

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
1  27.0    Male        1         13           3250                     28   
2  34.0   Other        1         16           4000                     35   
3   NaN  Female        2         20           5000                     45   
4  47.0    Male        1         24           6000                     77   
5   NaN    Male        4          4           1000                      4   
6  41.0   Other        2          7           1750                     14   

   Donated2020  
0            1  
1            1  
2            1  
3            1  
4            0  
5            0  
6            1

In [195]:
bd2['Recency']>2

0    False
1    False
2    False
3    False
4    False
5     True
6    False
Name: Recency, dtype: bool

In [198]:
bd2[bd2['Recency']>2]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
5  NaN   Male        4          4           1000                      4   

   Donated2020  
5            0

In [199]:
atmost32=bd2['Age']<=32
atmost32

0    False
1     True
2    False
3    False
4    False
5    False
6    False
Name: Age, dtype: bool

In [200]:
bd2[atmost32]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
1  27.0   Male        1         13           3250                     28   

   Donated2020  
1            1

In [201]:
bd2[bd2['Age']<=32]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
1  27.0   Male        1         13           3250                     28   

   Donated2020  
1            1

In [202]:
younger32=bd2['Age']<32
bd2[younger32]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
1  27.0   Male        1         13           3250                     28   

   Donated2020  
1            1

In [203]:
# patients with pregnancies not equal to 1 (either 0 or more than 1)
Recency1=(bd2['Recency']!=1)
bd2[Recency1]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
3   NaN  Female        2         20           5000                     45   
5   NaN    Male        4          4           1000                      4   
6  41.0   Other        2          7           1750                     14   

   Donated2020  
0            1  
3            1  
5            0  
6            1

In [204]:
# patients with BP at least 64 AND being pregnant more than once
Frequency64=bd2['Frequency']>=50
Recency1=bd2['Recency']>1
bd2[Frequency64 & Recency1]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   

   Donated2020  
0            1

In [205]:
bd2[(bd2['Frequency']>=50)&(bd2['Recency']>1)]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   

   Donated2020  
0            1

In [206]:
## in the original df
# the number of patiets patients 
# with BP at least 64 AND being pregnant more than once
Frequency64=bd['Frequency']>=50
Recency1=bd['Recency']>1
bd[Frequency64 & Recency1].shape

(1, 7)

In [207]:
len(bd[Frequency64 & Recency1])

1

## Conditions

In [208]:
# back to df2
# patients with BMI more than 30 OR being pregnant exactly once
# OR sing (|), shift+baclslash (right above Enter key)
TotalFromDonation30=bd2['TimeFromFirstDonation']>30
Recency1=(bd2['Recency']==1)
bd2[TotalFromDonation30 | Recency1]

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0    Male        2         50          12500                     98   
1  27.0    Male        1         13           3250                     28   
2  34.0   Other        1         16           4000                     35   
3   NaN  Female        2         20           5000                     45   
4  47.0    Male        1         24           6000                     77   

   Donated2020  
0            1  
1            1  
2            1  
3            1  
4            0

In [212]:
# paranthsese matter!
# patients (younger than 32 AND BP above 65) OR Glucose is 148
con1=bd2['Age']<32
con2=bd2['TimeFromFirstDonation']>65
con3=bd2['TotalDonation']==4000
bd2[(con1 & con2) | con3]

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
2  34.0  Other        1         16           4000                     35   

   Donated2020  
2            1

In [213]:
bd2[con1 & (con2 | con3)]

Empty DataFrame
Columns: [Age, Gender, Recency, Frequency, TotalDonation, TimeFromFirstDonation, Donated2020]
Index: []

## Handing Missing Value

In [218]:
bd_miss=pd.read_csv('blood_donation.csv')
bd_miss

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

In [219]:
bd_miss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Age                    850 non-null    float64
 1   Gender                 861 non-null    object 
 2   Recency                861 non-null    int64  
 3   Frequency              861 non-null    int64  
 4   TotalDonation          861 non-null    int64  
 5   TimeFromFirstDonation  861 non-null    int64  
 6   Donated2020            861 non-null    int64  
dtypes: float64(1), int64(5), object(1)
memory usage: 47.2+ KB


In [220]:
bd_miss.describe()

Age     Recency   Frequency  TotalDonation  \
count  850.000000  861.000000  861.000000     861.000000   
mean    44.011765    9.047619    5.695703    1420.905923   
std     10.549557    7.707822    5.510062    1374.249771   
min     16.000000    1.000000    1.000000     250.000000   
25%     38.000000    3.000000    2.000000     500.000000   
50%     45.000000    7.000000    4.000000    1150.000000   
75%     52.000000   14.000000    7.000000    1850.000000   
max     60.000000   74.000000   50.000000   12500.000000   

       TimeFromFirstDonation  Donated2020  
count             861.000000   861.000000  
mean               33.771196     0.337979  
std                23.144187     0.473296  
min                 2.000000     0.000000  
25%                16.000000     0.000000  
50%                28.000000     0.000000  
75%                46.000000     1.000000  
max                98.000000     1.000000

In [221]:
# drop rows with missing (the default)
bd_miss.dropna()

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
4    47.0    Male        1         24           6000                     77   
6    41.0   Other        2          7           1750                     14   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
4              0  
6              1  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[850 rows x 7 columns]

In [222]:
# dropping columns with missing
# if we want make the drops permanent, we set inplace to True
bd_miss.dropna(axis=1)

Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0      Male        2         50          12500                     98   
1      Male        1         13           3250                     28   
2     Other        1         16           4000                     35   
3    Female        2         20           5000                     45   
4      Male        1         24           6000                     77   
..      ...      ...        ...            ...                    ...   
856    Male        7          9           2350                     45   
857  Female        2         10           2450                     45   
858    Male       10          8           1700                     24   
859  Female        8          7           1550                     42   
860  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 6 columns]

In [223]:
bd_miss

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

## filling or imputing missing value

In [225]:
bd_miss.mean()

Age                        44.011765
Recency                     9.047619
Frequency                   5.695703
TotalDonation            1420.905923
TimeFromFirstDonation      33.771196
Donated2020                 0.337979
dtype: float64

In [226]:
# filling missing values with mean
bd_miss.fillna(value=bd_miss.mean(),inplace=True)
bd_miss

Age  Gender  Recency  Frequency  TotalDonation  \
0    42.000000    Male        2         50          12500   
1    27.000000    Male        1         13           3250   
2    34.000000   Other        1         16           4000   
3    44.011765  Female        2         20           5000   
4    47.000000    Male        1         24           6000   
..         ...     ...      ...        ...            ...   
856  33.000000    Male        7          9           2350   
857  34.000000  Female        2         10           2450   
858  28.000000    Male       10          8           1700   
859  21.000000  Female        8          7           1550   
860  38.000000  Female        6          8           2000   

     TimeFromFirstDonation  Donated2020  
0                       98            1  
1                       28            1  
2                       35            1  
3                       45            1  
4                       77            0  
..                     ...          ...  
856                     45            1  
857                     45            1  
858                     24            1  
859                     42            1  
860                     11            1  

[861 rows x 7 columns]

In [232]:
# mode to fill categorical variables
bd_miss['Gender'].mode()

0    Male
dtype: object

In [237]:
bd_miss['Gender'].value_counts() - important

Male      435
Female    414
Other      12
Name: Gender, dtype: int64

In [238]:
bd_miss.fillna(value={'Gender':'Female'},inplace=True)
bd_miss

Age  Gender  Recency  Frequency  TotalDonation  \
0    42.000000    Male        2         50          12500   
1    27.000000    Male        1         13           3250   
2    34.000000   Other        1         16           4000   
3    44.011765  Female        2         20           5000   
4    47.000000    Male        1         24           6000   
..         ...     ...      ...        ...            ...   
856  33.000000    Male        7          9           2350   
857  34.000000  Female        2         10           2450   
858  28.000000    Male       10          8           1700   
859  21.000000  Female        8          7           1550   
860  38.000000  Female        6          8           2000   

     TimeFromFirstDonation  Donated2020  
0                       98            1  
1                       28            1  
2                       35            1  
3                       45            1  
4                       77            0  
..                     ...          ...  
856                     45            1  
857                     45            1  
858                     24            1  
859                     42            1  
860                     11            1  

[861 rows x 7 columns]

# Week 6  Monday Class 10

In [759]:
bd3=pd.read_csv('blood_donation.csv')
bd3.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [761]:
bd3['Gender'].value_counts()

Male      435
Female    414
Other      12
Name: Gender, dtype: int64

In [762]:
bd3['Donated2020'].value_counts()

0    570
1    291
Name: Donated2020, dtype: int64

In [764]:
# create features and target sets
X_bd3, y_bd3=bd3.iloc[:,:-1], bd3['Donated2020']
# check our work
display(X_bd3.head(2))
display(y_bd3.head(2))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

0    1
1    1
Name: Donated2020, dtype: int64

## Handling Categorical Features

In [387]:
bd3=pd.read_csv('blood_donation.csv')
bd3.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [395]:
bd3.dropna(axis=1, inplace=True)

In [397]:
X_bd3, y_bd3=bd3.iloc[:,:-1], bd3['Donated2020']

In [398]:
X_dummies=pd.get_dummies(X_bd3)
X_dummies.head()

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Gender_Female  \
0        2         50          12500                     98              0   
1        1         13           3250                     28              0   
2        1         16           4000                     35              0   
3        2         20           5000                     45              1   
4        1         24           6000                     77              0   

   Gender_Male  Gender_Other  
0            1             0  
1            1             0  
2            0             1  
3            0             0  
4            1             0

In [399]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [401]:
X_train, X_test, y_train, y_test=train_test_split(X_dummies, y_bd3, test_size=.25, random_state=0)

In [409]:
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [410]:
print('knn acc on train: {:.2%}'.format(knn.score(X_train, y_train)))
print('knn acc on test: {:.2%}'.format(knn.score(X_test, y_test)))

knn acc on train: 80.62%
knn acc on test: 75.00%


In [411]:
X_bd3.head(1)

Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0   Male        2         50          12500                     98

In [414]:
p1=[35,1,1,45,12000,90,1]
knn.predict ([p1])

array([0])

## Categoraical data (West)

In [869]:
bd3.dropna(axis=1, inplace=True)

In [870]:
# create features and target sets
X_bd3, y_bd3=bd3.iloc[:,:-1], bd3['Donated2020']
# check our work
display(X_bd3.head(2))
display(y_bd3.head(2))

Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0   Male        2         50          12500                     98
1   Male        1         13           3250                     28

0    1
1    1
Name: Donated2020, dtype: int64

In [871]:
# in feature set, handle all potential categorical features
X_bd3['Gender']=X_bd3['Gender'].astype(str)
X_dummies=pd.get_dummies(X_bd3)
X_dummies.head(2)

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Gender_Female  \
0        2         50          12500                     98              0   
1        1         13           3250                     28              0   

   Gender_Male  Gender_Other  
0            1             0  
1            1             0

In [872]:
X_train, X_test, y_train, y_test=train_test_split(X_dummies, y_bd3, random_state=0)

In [873]:
from sklearn.linear_model import LinearRegression

In [874]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [875]:
X_train.dtypes

Recency                  int64
Frequency                int64
TotalDonation            int64
TimeFromFirstDonation    int64
Gender_Female            uint8
Gender_Male              uint8
Gender_Other             uint8
dtype: object

In [876]:
lr.fit(X_train,y_train)

LinearRegression()

In [877]:
print('lr R2 on train: {:.2%}'.format(lr.score(X_train, y_train)))
print('lr R2 on test: {:.2%}'.format(lr.score(X_test, y_test)))

lr R2 on train: 14.73%
lr R2 on test: 17.67%


In [878]:
sample1=X_test.iloc[:3]
sample1

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Gender_Female  \
55         4         19           4750                     69              1   
823        9         11           2500                     29              0   
568        4          6           1500                     35              0   

     Gender_Male  Gender_Other  
55             0             0  
823            1             0  
568            1             0

In [879]:
lr.predict(sample1).round()

array([1., 0., 0.])

In [880]:
y_test.head(3)

55     1
823    1
568    1
Name: Donated2020, dtype: int64

# Week 4  Wednesday Class 7

## KNN classifier

In [741]:
df1=pd.read_csv('blood_donation.csv')
df1.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [742]:
df1.dropna(axis=0, inplace=True)

In [743]:
X_df1, y_df1=df1.iloc[:,:-1], df1['Donated2020']
X_df1.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

In [744]:
X_dummies=pd.get_dummies(X_df1)
X_dummies.head()

Age  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0        2         50          12500                     98   
1  27.0        1         13           3250                     28   
2  34.0        1         16           4000                     35   
4  47.0        1         24           6000                     77   
6  41.0        2          7           1750                     14   

   Gender_Female  Gender_Male  Gender_Other  
0              0            1             0  
1              0            1             0  
2              0            0             1  
4              0            1             0  
6              0            0             1

In [745]:
# we need to konw the problem
# we read the data
# creating features and target sets
# import the machine learning algorith (class)
# define the model (specifying our model's parameters values)
# fit (train) the model
# evaluate the performance of our model
# use the model to make predictions for new unseen data

In [746]:
# creating features and target sets
# first two cols are our features
# 'Donated2020' is the target var

In [747]:
y_df1.head(2)

0    1
1    1
Name: Donated2020, dtype: int64

In [748]:
from sklearn.neighbors import KNeighborsClassifier

In [749]:
knn_cls=KNeighborsClassifier(n_neighbors=3)

In [750]:
knn_cls.fit(X_dummies, y_df1)

KNeighborsClassifier(n_neighbors=3)

In [751]:
knn_cls.score(X_dummies,y_df1)

0.9435294117647058

In [752]:
w1=[40,1,45,12000,30,1,0,1]
w2=[45,0,34,5000,50,0,1,1]
w3=[32,1,44,7000,62,1,0,1]
# prediction
knn_cls.predict([w1,w2,w3])

array([1, 1, 0])

In [861]:
knn_cls.predict(X_dummies)

array([1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## Fair Evaluation 

In [445]:
X_bd3=bd3.iloc[:,:]
y_bd3=bd3['Donated2020']
display(X_bd3.head(2))
display(y_bd3.head(2))

Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0   Male        2         50          12500                     98   
1   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

0    1
1    1
Name: Donated2020, dtype: int64

In [446]:
from sklearn.model_selection import train_test_split

In [448]:
X_train, X_test, y_train, y_test=train_test_split(X_bd3,
                                                  y_bd3,
                                                 random_state=0)

In [450]:
print('initial features set size:',X_bd3.shape)
print('X_train shape:',X_train.shape)
print('X_test shape:',X_test.shape)

print('y_train shape:',y_train.shape)
print('y_test shape:',y_test.shape)

initial features set size: (861, 6)
X_train shape: (645, 6)
X_test shape: (216, 6)
y_train shape: (645,)
y_test shape: (216,)


# Week 5  Monday Class 8

## Cross-validation

In [881]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split

In [882]:
df1=pd.read_csv('blood_donation.csv')
df1.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [883]:
df1.dropna(inplace=True)

In [884]:
X_dummies=pd.get_dummies(X_df1)
X_dummies.head()

Age  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0        2         50          12500                     98   
1  27.0        1         13           3250                     28   
2  34.0        1         16           4000                     35   
4  47.0        1         24           6000                     77   
6  41.0        2          7           1750                     14   

   Gender_Female  Gender_Male  Gender_Other  
0              0            1             0  
1              0            1             0  
2              0            0             1  
4              0            1             0  
6              0            0             1

In [885]:
X_df1, y_df1=df1.iloc[:,:-1], df1['Donated2020']
display(X_df1.head(2))
display(y_df1.head(2))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

0    1
1    1
Name: Donated2020, dtype: int64

In [886]:
knn_cls_blood=KNeighborsClassifier(n_neighbors=9)

In [887]:
scores=cross_val_score(knn_cls_blood,X_dummies,y_df1,cv=6)
scores

array([0.76056338, 0.78169014, 0.79577465, 0.84507042, 0.92907801,
       0.97163121])

In [888]:
scores.mean()

0.847301301901242

In [889]:
print('Average test accuracy in a 6-fold cross val is: {:.2%}'.format(
    scores.mean()))

Average test accuracy in a 6-fold cross val is: 84.73%


## overfitting and Underfitting 

In [753]:
display(X_df1.head(1))
display(y_df1.head(1))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98

0    1
Name: Donated2020, dtype: int64

In [794]:
X_df1, y_df1=df1.iloc[:,:-1], df1['Donated2020']
display(X_df1.head(2))
display(y_df1.head(2))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

0    1
1    1
Name: Donated2020, dtype: int64

In [795]:
df1.dropna(inplace=True)

In [806]:
X_dummies=pd.get_dummies(X_df1)
X_dummies

Age  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0        2         50          12500                     98   
1    27.0        1         13           3250                     28   
2    34.0        1         16           4000                     35   
4    47.0        1         24           6000                     77   
6    41.0        2          7           1750                     14   
..    ...      ...        ...            ...                    ...   
856  33.0        7          9           2350                     45   
857  34.0        2         10           2450                     45   
858  28.0       10          8           1700                     24   
859  21.0        8          7           1550                     42   
860  38.0        6          8           2000                     11   

     Gender_Female  Gender_Male  Gender_Other  
0                0            1             0  
1                0            1             0  
2                0            0             1  
4                0            1             0  
6                0            0             1  
..             ...          ...           ...  
856              0            1             0  
857              1            0             0  
858              0            1             0  
859              1            0             0  
860              1            0             0  

[850 rows x 8 columns]

In [807]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split

In [808]:
X_train, X_test, y_train, y_test=train_test_split(X_dummies,y_df1,
                                                  random_state=0)

In [809]:
knn1=KNeighborsClassifier(n_neighbors=1)
knn5=KNeighborsClassifier(n_neighbors=5)
knn9=KNeighborsClassifier(n_neighbors=9)
knn29=KNeighborsClassifier(n_neighbors=29)

In [810]:
knn1.fit(X_train,y_train)
knn5.fit(X_train,y_train)
knn9.fit(X_train,y_train)
knn29.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=29)

In [811]:
print('knn1 acc on train: {:.2%}'.format(knn1.score(X_train,y_train)))
print('knn1 acc on test: {:.2%}'.format(knn1.score(X_test,y_test)),'\n')

print('knn5 acc on train: {:.2%}'.format(knn5.score(X_train,y_train)))
print('knn5 acc on test: {:.2%}'.format(knn5.score(X_test,y_test)),'\n')

print('knn9 acc on train: {:.2%}'.format(knn9.score(X_train,y_train)))
print('knn9 acc on test: {:.2%}'.format(knn9.score(X_test,y_test)),'\n')

print('knn29 acc on train: {:.2%}'.format(knn29.score(X_train,y_train)))
print('knn29 acc on test: {:.2%}'.format(knn29.score(X_test,y_test)))

knn1 acc on train: 99.53%
knn1 acc on test: 86.38% 

knn5 acc on train: 91.68%
knn5 acc on test: 89.20% 

knn9 acc on train: 88.54%
knn9 acc on test: 87.32% 

knn29 acc on train: 78.49%
knn29 acc on test: 76.53%


In [758]:
df1.shape

(850, 7)

## KNN Classifier

In [813]:
import pandas as pd

In [815]:
blood=pd.read_csv('blood_donation.csv')
blood.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [820]:
blood.dropna(inplace=True)

In [831]:
X_df5, y_df5=blood.iloc[:,:-1], blood['Donated2020']
display(X_df5.head(2))
display(y_df5.head(2))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

0    1
1    1
Name: Donated2020, dtype: int64

In [832]:
X_dummies=pd.get_dummies(X_df5)
X_dummies

Age  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0        2         50          12500                     98   
1    27.0        1         13           3250                     28   
2    34.0        1         16           4000                     35   
4    47.0        1         24           6000                     77   
6    41.0        2          7           1750                     14   
..    ...      ...        ...            ...                    ...   
856  33.0        7          9           2350                     45   
857  34.0        2         10           2450                     45   
858  28.0       10          8           1700                     24   
859  21.0        8          7           1550                     42   
860  38.0        6          8           2000                     11   

     Gender_Female  Gender_Male  Gender_Other  
0                0            1             0  
1                0            1             0  
2                0            0             1  
4                0            1             0  
6                0            0             1  
..             ...          ...           ...  
856              0            1             0  
857              1            0             0  
858              0            1             0  
859              1            0             0  
860              1            0             0  

[850 rows x 8 columns]

In [833]:
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split

In [834]:
X_train, X_test, y_train, y_test=train_test_split(X_dummies,y_df5,
                                                  random_state=0)

In [838]:
knn1=KNeighborsClassifier(n_neighbors=1)

In [839]:
knn1.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [840]:
print('knn1 acc on train: {:.2%}'.format(knn1.score(X_train,y_train)))
print('knn1 acc on test: {:.2%}'.format(knn1.score(X_test,y_test)),'\n')

knn1 acc on train: 99.53%
knn1 acc on test: 86.38% 



# Week 7 Monday Class 11

In [564]:
import pandas as pd

In [713]:
df1=pd.read_csv('blood_donation.csv')
df1

Age  Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0    42.0    Male        2         50          12500                     98   
1    27.0    Male        1         13           3250                     28   
2    34.0   Other        1         16           4000                     35   
3     NaN  Female        2         20           5000                     45   
4    47.0    Male        1         24           6000                     77   
..    ...     ...      ...        ...            ...                    ...   
856  33.0    Male        7          9           2350                     45   
857  34.0  Female        2         10           2450                     45   
858  28.0    Male       10          8           1700                     24   
859  21.0  Female        8          7           1550                     42   
860  38.0  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 7 columns]

In [736]:
df1.dropna(axis=0, inplace=True)

In [737]:
df1

Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0      Male        2         50          12500                     98   
1      Male        1         13           3250                     28   
2     Other        1         16           4000                     35   
3    Female        2         20           5000                     45   
4      Male        1         24           6000                     77   
..      ...      ...        ...            ...                    ...   
856    Male        7          9           2350                     45   
857  Female        2         10           2450                     45   
858    Male       10          8           1700                     24   
859  Female        8          7           1550                     42   
860  Female        6          8           2000                     11   

     Donated2020  
0              1  
1              1  
2              1  
3              1  
4              0  
..           ...  
856            1  
857            1  
858            1  
859            1  
860            1  

[861 rows x 6 columns]

In [738]:
X_dummies=pd.get_dummies(df1)
X_dummies.head()

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Donated2020  \
0        2         50          12500                     98            1   
1        1         13           3250                     28            1   
2        1         16           4000                     35            1   
3        2         20           5000                     45            1   
4        1         24           6000                     77            0   

   Gender_Female  Gender_Male  Gender_Other  
0              0            1             0  
1              0            1             0  
2              0            0             1  
3              1            0             0  
4              0            1             0

In [739]:
df1[df1['Donated2020']==1].describe().round(2)

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Donated2020
count   291.00     291.00         291.00                 291.00        291.0
mean      5.66       7.45        1852.75                  31.81          1.0
std       4.44       6.42        1598.39                  19.87          0.0
min       1.00       1.00         250.00                   2.00          1.0
25%       2.00       4.00        1050.00                  16.00          1.0
50%       4.00       6.00        1500.00                  30.00          1.0
75%       8.00       9.00        2175.00                  42.00          1.0
max      26.00      50.00       12500.00                  98.00          1.0

In [740]:
df1[df1['Donated2020']==0].describe().round(2)

Recency  Frequency  TotalDonation  TimeFromFirstDonation  Donated2020
count   570.00     570.00         570.00                 570.00        570.0
mean     10.78       4.80        1200.44                  34.77          0.0
std       8.42       4.75        1186.69                  24.61          0.0
min       1.00       1.00         250.00                   2.00          0.0
25%       4.00       2.00         500.00                  16.00          0.0
50%      11.00       3.00         750.00                  28.00          0.0
75%      16.00       6.00        1500.00                  52.00          0.0
max      74.00      44.00       11000.00                  98.00          0.0

In [725]:
X_df1, y_df1=df1[['TotalDonation']], df1['Donated2020']
display(X_df1.head(2))
display(y_df1.head(2))

TotalDonation
0          12500
1           3250

0    1
1    1
Name: Donated2020, dtype: int64

In [726]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [727]:
X_train, X_test, y_train, y_test=train_test_split(X_df1, y_df1, test_size=0.2, random_state=0)

In [728]:
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

LogisticRegression()

In [729]:
print('log reg acc on train: {:.2%}'.format(log_reg.score(X_train, y_train)))
print('log reg acc on test: {:.2%}'.format(log_reg.score(X_test, y_test)))

log reg acc on train: 65.41%
log reg acc on test: 63.58%


In [730]:
p1=[4000]
p2=[5400]
p3=[10000]
log_reg.predict([p1,p2,p3])

array([1, 1, 1])

In [731]:
import numpy as np
np.set_printoptions(suppress=True)

In [732]:
log_reg.predict_proba([p1,p2,p3]).round(4)

array([[0.455 , 0.545 ],
       [0.3388, 0.6612],
       [0.0933, 0.9067]])

In [733]:
log_reg.classes_

array([0, 1])

In [734]:
log_reg.coef_.round(4)

array([[0.0003]])

In [735]:
log_reg.intercept_.round(4)

array([-1.215])

## Controlling the complexity of log regression, using parameter 'c'

In [596]:
df1.dropna(axis=0, inplace=True)

In [597]:
X_dummies=pd.get_dummies(X_df1)
X_dummies.head()

Age  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0        2         50          12500                     98   
1  27.0        1         13           3250                     28   
2  34.0        1         16           4000                     35   
4  47.0        1         24           6000                     77   
6  41.0        2          7           1750                     14   

   Gender_Female  Gender_Male  Gender_Other  
0              0            1             0  
1              0            1             0  
2              0            0             1  
4              0            1             0  
6              0            0             1

In [598]:
X_df1, y_df1=df1.iloc[:,:-1], df1['Donated2020']
display(X_df1.head(2))
display(y_df1.head(2))

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation
0  42.0   Male        2         50          12500                     98
1  27.0   Male        1         13           3250                     28

0    1
1    1
Name: Donated2020, dtype: int64

In [599]:
from sklearn.preprocessing import MinMaxScaler

In [601]:
scaler1=MinMaxScaler()
X_df1_trns=scaler1.fit_transform(X_dummies)
X_df1_trns

array([[0.59090909, 0.01369863, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.25      , 0.        , 0.24489796, ..., 0.        , 1.        ,
        0.        ],
       [0.40909091, 0.        , 0.30612245, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.27272727, 0.12328767, 0.14285714, ..., 0.        , 1.        ,
        0.        ],
       [0.11363636, 0.09589041, 0.12244898, ..., 1.        , 0.        ,
        0.        ],
       [0.5       , 0.06849315, 0.14285714, ..., 1.        , 0.        ,
        0.        ]])

## Validation Curve Functions

In [602]:
from sklearn.model_selection import validation_curve

In [603]:
C_range=[.1,.5,1,10,100,200]

In [604]:
train_scores, test_scores=validation_curve(LogisticRegression(max_iter=1000), X_df1_trns, y_df1, param_name='C',
                                           param_range=C_range, cv=4)

In [605]:
train_scores.round(4)

array([[0.8838, 0.8713, 0.8574, 0.8433],
       [0.9403, 0.9419, 0.9201, 0.8997],
       [0.9419, 0.9403, 0.9263, 0.9075],
       [0.9372, 0.9388, 0.9248, 0.8981],
       [0.9309, 0.9388, 0.9169, 0.8997],
       [0.9309, 0.9388, 0.9169, 0.8966]])

In [606]:
test_scores.round(4)

array([[0.8122, 0.8216, 0.8585, 0.9245],
       [0.8826, 0.8592, 0.9434, 1.    ],
       [0.8873, 0.8732, 0.9387, 1.    ],
       [0.8779, 0.8873, 0.934 , 0.9953],
       [0.8685, 0.8826, 0.9245, 0.9906],
       [0.8685, 0.8826, 0.9245, 0.9858]])

In [607]:
train_scores.mean(axis=1).round(4)

array([0.8639, 0.9255, 0.929 , 0.9247, 0.9216, 0.9208])

In [608]:
test_scores.mean(axis=1).round(4)

array([0.8542, 0.9213, 0.9248, 0.9236, 0.9166, 0.9154])

In [609]:
C_range

[0.1, 0.5, 1, 10, 100, 200]

# Week 7 Wednesday Class 12

In [610]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, validation_curve
from sklearn.svm import LinearSVC

In [611]:
X_df1, y_df1=df1[['TotalDonation']], df1['Donated2020']
display(X_df1.head(2))
display(y_df1.head(2))

TotalDonation
0          12500
1           3250

0    1
1    1
Name: Donated2020, dtype: int64

In [612]:
X_df1.describe()

TotalDonation
count     850.000000
mean     1410.470588
std      1372.361721
min       250.000000
25%       500.000000
50%      1050.000000
75%      1750.000000
max     12500.000000

## transforming feature dataset

In [638]:
df2=pd.read_csv('blood_donation.csv')
df2.head(2)

Age Gender  Recency  Frequency  TotalDonation  TimeFromFirstDonation  \
0  42.0   Male        2         50          12500                     98   
1  27.0   Male        1         13           3250                     28   

   Donated2020  
0            1  
1            1

In [650]:
df2.dropna(axis=0, inplace=True)

In [651]:
X_df2, y_df2=df2[['TotalDonation']], df2['Donated2020']
display(X_df2.head(2))
display(y_df2.head(2))

TotalDonation
0          12500
1           3250

0    1
1    1
Name: Donated2020, dtype: int64

In [682]:
scaler2=MinMaxScaler()
X_df2_trns=scaler2.fit_transform(X_df2)
X_df2_trns

array([[1.        ],
       [0.24489796],
       [0.30612245],
       [0.46938776],
       [0.12244898],
       [0.2244898 ],
       [0.16326531],
       [0.91836735],
       [0.44897959],
       [0.04081633],
       [0.24489796],
       [0.10204082],
       [0.08163265],
       [0.26530612],
       [0.28571429],
       [0.10204082],
       [0.04081633],
       [0.04081633],
       [0.20408163],
       [0.10204082],
       [0.10204082],
       [0.16326531],
       [0.26530612],
       [0.10204082],
       [0.2244898 ],
       [0.08163265],
       [0.14285714],
       [0.26530612],
       [0.18367347],
       [0.18367347],
       [0.16326531],
       [0.30612245],
       [0.14285714],
       [0.2244898 ],
       [0.26530612],
       [0.12244898],
       [0.24489796],
       [0.08163265],
       [0.08163265],
       [0.08163265],
       [0.3877551 ],
       [0.16326531],
       [0.16326531],
       [0.02040816],
       [0.02040816],
       [0.02040816],
       [0.20408163],
       [0.204

In [683]:
X_train, X_test, y_train, y_test=train_test_split(X_df2_trns, y_df2, random_state=0)

In [684]:
svm1=LinearSVC(random_state=0)
svm1.fit(X_train,y_train)

LinearSVC(random_state=0)

In [685]:
svm1.coef_

array([[1.76633941]])

In [686]:
svm1.intercept_

array([-0.47374518])

In [687]:
print('svm acc on train: {:.2%}'.format(svm1.score(X_train, y_train)))
print('svm acc on test: {:.2%}'.format(svm1.score(X_test, y_test)))

svm acc on train: 64.52%
svm acc on test: 68.54%


In [690]:
b=[[12500],[2300],[5000]]
svm1.predict(b)

array([1, 1, 1])

In [692]:
b_trns=scaler2.transform(b)
b_trns

array([[1.        ],
       [0.16734694],
       [0.3877551 ]])

In [693]:
svm1.predict(b_trns)

array([1, 0, 1])

In [694]:
svm1.intercept_.round(2)

array([-0.47])

In [695]:
svm1.coef_.round(2)

array([[1.77]])

In [696]:
svm1.classes_

array([0, 1])

## transforming features set (Controlling the complexity of svm by change parareter 'C'

In [700]:
scaler3=MinMaxScaler()
X_df2_trns=scaler3.fit_transform(X_df2)
X_df2_trns

array([[1.        ],
       [0.24489796],
       [0.30612245],
       [0.46938776],
       [0.12244898],
       [0.2244898 ],
       [0.16326531],
       [0.91836735],
       [0.44897959],
       [0.04081633],
       [0.24489796],
       [0.10204082],
       [0.08163265],
       [0.26530612],
       [0.28571429],
       [0.10204082],
       [0.04081633],
       [0.04081633],
       [0.20408163],
       [0.10204082],
       [0.10204082],
       [0.16326531],
       [0.26530612],
       [0.10204082],
       [0.2244898 ],
       [0.08163265],
       [0.14285714],
       [0.26530612],
       [0.18367347],
       [0.18367347],
       [0.16326531],
       [0.30612245],
       [0.14285714],
       [0.2244898 ],
       [0.26530612],
       [0.12244898],
       [0.24489796],
       [0.08163265],
       [0.08163265],
       [0.08163265],
       [0.3877551 ],
       [0.16326531],
       [0.16326531],
       [0.02040816],
       [0.02040816],
       [0.02040816],
       [0.20408163],
       [0.204

In [698]:
LinearSVC()

LinearSVC()

In [702]:
rain_scores, test_scores=validation_curve(LinearSVC(random_state=0,max_iter=100000),
                                          X_df2_trns, y_df2,
                                          param_name='C',
                                          param_range=[.1, 1, 5, 10, 50, 100],
                                          cv=4)

In [703]:
train_scores.round(4)

array([[0.8838, 0.8713, 0.8574, 0.8433],
       [0.9403, 0.9419, 0.9201, 0.8997],
       [0.9419, 0.9403, 0.9263, 0.9075],
       [0.9372, 0.9388, 0.9248, 0.8981],
       [0.9309, 0.9388, 0.9169, 0.8997],
       [0.9309, 0.9388, 0.9169, 0.8966]])

In [704]:
test_scores.round(4)

array([[0.6667, 0.6901, 0.6509, 0.6604],
       [0.6526, 0.6761, 0.6321, 0.6557],
       [0.662 , 0.6761, 0.6321, 0.6557],
       [0.662 , 0.6761, 0.6321, 0.6557],
       [0.662 , 0.6761, 0.6321, 0.6557],
       [0.662 , 0.6761, 0.6321, 0.6557]])

In [705]:
print('average score in 4 folds for different C values:')
print('training:',train_scores.mean(axis=1).round(4))
print('test:',test_scores.mean(axis=1).round(4))

average score in 4 folds for different C values:
training: [0.8639 0.9255 0.929  0.9247 0.9216 0.9208]
test: [0.667  0.6541 0.6564 0.6564 0.6564 0.6564]


In [706]:
[.1, 1, 5, 10, 50, 100]

[0.1, 1, 5, 10, 50, 100]

In [707]:
train_scores.mean()

0.9142590783600637