In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import validation_curve
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split

In [2]:
%pwd

'/Users/ryanmaki'

In [5]:
bank_bal=pd.read_csv('OBA_410_Group_Data.csv')
bank_bal

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0             0                                           0.000000          
1             1                                           0.024277          
2             1                                           0.066933          
3             0                                           0.081412          
4             0                                           0.082826          
...         ...                                                ...          
6814          0                                           0.787988          
6815          0                                           0.818018          
6816          0                                           0.864964          
6817          0                                           0.971530          
6818          0                                           1.000000          

       ROA(A) before interest and % after tax  \
0                                    0.006923   
1                                    0.000000   
2                                    0.057185   
3                                    0.091256   
4                                    0.069287   
...                                       ...   
6814                                 0.804514   
6815                                 0.801570   
6816                                 0.942706   
6817                                 1.000000   
6818                                 0.947067   

       ROA(B) before interest and depreciation after tax  \
0                                              0.000000    
1                                              0.033514    
2                                              0.054821    
3                                              0.091761    
4                                              0.088388    
...                                                 ...    
6814                                           0.783928    
6815                                           0.814551    
6816                                           0.932598    
6817                                           1.000000    
6818                                           0.957760    

       Operating Gross Margin   Realized Sales Gross Margin  \
0                    0.593501                      0.593551   
1                    0.591324                      0.591324   
2                    0.601861                      0.601861   
3                    0.602935                      0.602935   
4                    0.646846                      0.646846   
...                       ...                           ...   
6814                 0.608015                      0.608015   
6815                 0.634983                      0.634983   
6816                 0.622371                      0.622371   
6817                 0.640035                      0.640035   
6818                 0.640684                      0.640684   

       Operating Profit Rate   Pre-tax net Interest Rate  \
0                   0.998775                    0.795533   
1                   0.994015                    0.791503   
2                   0.998825                    0.796779   
3                   0.973875                    0.767759   
4                   0.997083                    0.795795   
...                      ...                         ...   
6814                0.999147                    0.798222   
6815                0.999278                    0.797758   
6816                0.999308                    0.797793   
6817                0.999571                    0.798105   
6818                0.999507                    0.798029   

       After-tax net Interest Rate  \
0                         0.807547   
1                         0.803775   
2                         0.808717   
3                         0.781429   
4                         0.807815   
...                            ...   
6814                      0

In [6]:
# bank_bal.drop(bank_bal.iloc[:,10:], inplace=True, axis=1)

In [7]:
bank_bal=bank_bal.groupby('Bankrupt?',group_keys=False).apply(lambda x: x.sample(1000,replace=True,random_state=0))
bank_bal['Bankrupt?'].value_counts()

0    1000
1    1000
Name: Bankrupt?, dtype: int64

In [8]:
bank_bal

Bankrupt?   ROA(C) before interest and depreciation before interest  \
2935          0                                           0.495686          
2807          0                                           0.494028          
1834          0                                           0.478672          
3475          0                                           0.503924          
5150          0                                           0.536635          
...         ...                                                ...          
928           1                                           0.454346          
1791          1                                           0.477990          
368           1                                           0.417540          
1250          1                                           0.466728          
1             1                                           0.024277          

       ROA(A) before interest and % after tax  \
2935                                 0.550916   
2807                                 0.556149   
1834                                 0.541976   
3475                                 0.551297   
5150                                 0.597580   
...                                       ...   
928                                  0.513792   
1791                                 0.538323   
368                                  0.470726   
1250                                 0.490078   
1                                    0.000000   

       ROA(B) before interest and depreciation after tax  \
2935                                           0.542963    
2807                                           0.539697    
1834                                           0.531881    
3475                                           0.549280    
5150                                           0.580813    
...                                                 ...    
928                                            0.506023    
1791                                           0.529632    
368                                            0.460892    
1250                                           0.501097    
1                                              0.033514    

       Operating Gross Margin   Realized Sales Gross Margin  \
2935                 0.599209                      0.599209   
2807                 0.603273                      0.603021   
1834                 0.605226                      0.605226   
3475                 0.607064                      0.607064   
5150                 0.610466                      0.610141   
...                       ...                           ...   
928                  0.597522                      0.597522   
1791                 0.616966                      0.616930   
368                  0.600852                      0.600852   
1250                 0.607850                      0.607850   
1                    0.591324                      0.591324   

       Operating Profit Rate   Pre-tax net Interest Rate  \
2935                0.999001                    0.797404   
2807                0.999016                    0.797448   
1834                0.999008                    0.797419   
3475                0.998987                    0.797522   
5150                0.999138                    0.797629   
...                      ...                         ...   
928                 0.998899                    0.797237   
1791                0.999190                    0.797473   
368                 0.998935                    0.797160   
1250                0.998855                    0.797196   
1                   0.994015                    0.791503   

       After-tax net Interest Rate  \
2935                      0.809320   
2807                      0.809353   
1834                      0.809341   
3475                      0.809440   
5150                      0.809496   
...                            ...   
928                       0

# Logistic Regression¶

In [9]:
bank_bal[bank_bal['Bankrupt?']==1].describe().round(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count     1000.0                                            1000.00          
mean         1.0                                               0.42          
std          0.0                                               0.08          
min          1.0                                               0.02          
25%          1.0                                               0.39          
50%          1.0                                               0.44          
75%          1.0                                               0.47          
max          1.0                                               0.58          

        ROA(A) before interest and % after tax  \
count                                  1000.00   
mean                                      0.46   
std                                       0.11   
min                                       0.00   
25%                                       0.43   
50%                                       0.49   
75%                                       0.53   
max                                       0.58   

        ROA(B) before interest and depreciation after tax  \
count                                            1000.00    
mean                                                0.46    
std                                                 0.09    
min                                                 0.03    
25%                                                 0.44    
50%                                                 0.49    
75%                                                 0.52    
max                                                 0.62    

        Operating Gross Margin   Realized Sales Gross Margin  \
count                  1000.00                       1000.00   
mean                      0.60                          0.60   
std                       0.01                          0.01   
min                       0.53                          0.53   
25%                       0.59                          0.59   
50%                       0.60                          0.60   
75%                       0.60                          0.60   
max                       0.67                          0.67   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count                 1000.00                     1000.00   
mean                     1.00                        0.80   
std                      0.00                        0.00   
min                      0.99                        0.76   
25%                      1.00                        0.80   
50%                      1.00                        0.80   
75%                      1.00                        0.80   
max                      1.00                        0.80   

        After-tax net Interest Rate  \
count                       1000.00   
mean                           0.81   
std                            0.00   
min                            0.76   
25%                            0.81   
50%                            0.81   
75%                            0.81   
max                            0.81   

        Non-industry income and expenditure/revenue  ...  \
count                                       1000.00  ...   
mean                                           0.30  ...   
std                                            0.01  ...   
min                                            0.24  ...   
25%                                            0.30  ...   
50%                                            0.30  ...   
75%                                            0.30  ...   
max                                            0.31  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                      1000.00                1.000000e+03   
mean                          0.74                5.630000e+07   
std                           0.08                5.971907e+08   
min                

In [10]:
bank_bal[bank_bal['Bankrupt?']==0].describe().round(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count     1000.0                                            1000.00          
mean         0.0                                               0.51          
std          0.0                                               0.06          
min          0.0                                               0.00          
25%          0.0                                               0.48          
50%          0.0                                               0.50          
75%          0.0                                               0.54          
max          0.0                                               1.00          

        ROA(A) before interest and % after tax  \
count                                  1000.00   
mean                                      0.56   
std                                       0.06   
min                                       0.01   
25%                                       0.54   
50%                                       0.56   
75%                                       0.59   
max                                       0.95   

        ROA(B) before interest and depreciation after tax  \
count                                            1000.00    
mean                                                0.56    
std                                                 0.06    
min                                                 0.00    
25%                                                 0.53    
50%                                                 0.55    
75%                                                 0.59    
max                                                 0.96    

        Operating Gross Margin   Realized Sales Gross Margin  \
count                  1000.00                       1000.00   
mean                      0.61                          0.61   
std                       0.01                          0.01   
min                       0.45                          0.45   
25%                       0.60                          0.60   
50%                       0.61                          0.61   
75%                       0.61                          0.61   
max                       0.66                          0.66   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count                 1000.00                     1000.00   
mean                     1.00                        0.80   
std                      0.01                        0.02   
min                      0.61                        0.16   
25%                      1.00                        0.80   
50%                      1.00                        0.80   
75%                      1.00                        0.80   
max                      1.00                        0.81   

        After-tax net Interest Rate  \
count                       1000.00   
mean                           0.81   
std                            0.03   
min                            0.00   
25%                            0.81   
50%                            0.81   
75%                            0.81   
max                            0.82   

        Non-industry income and expenditure/revenue  ...  \
count                                       1000.00  ...   
mean                                           0.30  ...   
std                                            0.01  ...   
min                                            0.00  ...   
25%                                            0.30  ...   
50%                                            0.30  ...   
75%                                            0.30  ...   
max                                            0.33  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                      1000.00                     1000.00   
mean                          0.81                        0.01   
std                           0.04                        0.04   
min                

In [11]:
X_bank, y_bank=bank_bal.iloc[:,1:], bank_bal['Bankrupt?'] 
display(X_bank.head(2))
display(y_bank.head(2))

ROA(C) before interest and depreciation before interest  \
2935                                           0.495686          
2807                                           0.494028          

       ROA(A) before interest and % after tax  \
2935                                 0.550916   
2807                                 0.556149   

       ROA(B) before interest and depreciation after tax  \
2935                                           0.542963    
2807                                           0.539697    

       Operating Gross Margin   Realized Sales Gross Margin  \
2935                 0.599209                      0.599209   
2807                 0.603273                      0.603021   

       Operating Profit Rate   Pre-tax net Interest Rate  \
2935                0.999001                    0.797404   
2807                0.999016                    0.797448   

       After-tax net Interest Rate  \
2935                      0.809320   
2807                      0.809353   

       Non-industry income and expenditure/revenue  \
2935                                      0.303483   
2807                                      0.303527   

       Continuous interest rate (after tax)  ...   Net Income to Total Assets  \
2935                               0.781574  ...                     0.804195   
2807                               0.781613  ...                     0.806766   

       Total assets to GNP price   No-credit Interval   Gross Profit to Sales  \
2935                    0.005798             0.623865                0.599205   
2807                    0.001678             0.623481                0.603273   

       Net Income to Stockholder's Equity   Liability to Equity  \
2935                             0.840688              0.279388   
2807                             0.841082              0.281947   

       Degree of Financial Leverage (DFL)  \
2935                             0.027243   
2807                             0.027068   

       Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
2935                                           0.566668                   1   
2807                                           0.566204                   1   

       Equity to Liability  
2935              0.030801  
2807              0.023555  

[2 rows x 95 columns]

2935    0
2807    0
Name: Bankrupt?, dtype: int64

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
dt=DecisionTreeClassifier(random_state=0)
dt.fit(X_bank,y_bank)

DecisionTreeClassifier(random_state=0)

In [14]:
sum(dt.feature_importances_>.01)

16

In [15]:
X_bank_sel=X_bank[X_bank.columns[dt.feature_importances_>.01]]
X_bank_sel.head()

Continuous interest rate (after tax)   Operating Expense Rate  \
2935                               0.781574             5.820000e+09   
2807                               0.781613             1.038420e-04   
1834                               0.781601             1.474370e-04   
3475                               0.781594             1.973910e-04   
5150                               0.781749             9.560000e+09   

       Interest-bearing debt interest rate   Net Value Per Share (A)  \
2935                              0.000672                  0.177447   
2807                              0.000359                  0.190342   
1834                              0.000141                  0.171421   
3475                              0.000484                  0.189415   
5150                              0.000000                  0.234419   

       Persistent EPS in the Last Four Seasons   Operating Profit Growth Rate  \
2935                                  0.217831                       0.848084   
2807                                  0.224355                       0.848025   
1834                                  0.218020                       0.848012   
3475                                  0.216129                       0.848184   
5150                                  0.245722                       0.848215   

       Total Asset Growth Rate   Quick Ratio   Interest Expense Ratio  \
2935              5.550000e+09      0.007517                 0.632188   
2807              8.000000e+09      0.003586                 0.631575   
1834              5.830000e+09      0.006185                 0.631163   
3475              1.039850e-04      0.004459                 0.632241   
5150              7.490000e+09      0.022148                 0.630614   

       Total debt/Total net worth   Accounts Receivable Turnover  \
2935                     0.006354                       0.001469   
2807                     0.009883                       0.001108   
1834                     0.007635                       0.000363   
3475                     0.010284                       0.002682   
5150                     0.001962                       0.001175   

       Operating profit per person   Allocation rate per person  \
2935                      0.396373                     0.005721   
2807                      0.398295                     0.006320   
1834                      0.394677                     0.015585   
3475                      0.392879                     0.048975   
5150                      0.403247                     0.002276   

       Cash Turnover Rate   Cash Flow to Sales  \
2935         2.580000e+08             0.671572   
2807         6.650000e+09             0.671579   
1834         1.250000e+09             0.671575   
3475         2.072150e-04             0.671454   
5150         2.695690e-04             0.671648   

       Interest Coverage Ratio (Interest expense to EBIT)  
2935                                           0.566668    
2807                                           0.566204    
1834                                           0.565898    
3475                                           0.566266    
5150                                           0.565160

In [16]:
scaler1=MinMaxScaler()
X_bank_trns=scaler1.fit_transform(X_bank_sel)
X_bank_trns

array([[9.78771560e-01, 5.87285570e-01, 7.00069792e-13, ...,
        2.58258258e-02, 9.72108922e-01, 5.79849651e-01],
       [9.78829637e-01, 3.85065590e-16, 3.73995833e-13, ...,
        6.65665666e-01, 9.72118950e-01, 5.78705083e-01],
       [9.78812680e-01, 4.78415742e-15, 1.46889583e-13, ...,
        1.25125125e-01, 9.72112531e-01, 5.77951033e-01],
       ...,
       [9.78397658e-01, 5.07578204e-15, 8.43834375e-13, ...,
        1.39725726e-14, 9.72129663e-01, 5.72450276e-01],
       [9.78439202e-01, 2.44808274e-14, 4.43794792e-13, ...,
        9.09909910e-02, 9.72104756e-01, 5.71057391e-01],
       [9.69751507e-01, 4.86501715e-13, 0.00000000e+00, ...,
        2.34577578e-14, 9.72031743e-01, 5.76126590e-01]])

In [17]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_trns, y_bank, test_size=0.2, random_state=0)

In [18]:
train_scores_log_reg, test_scores_log_reg=validation_curve(LogisticRegression(penalty='l1', solver='saga', max_iter=100000), X_train, y_train, param_name='C',
                                           param_range=[0.01,0.05,1,5,10,20], cv=4)

In [19]:
train_scores_log_reg.mean(axis=1).round(4)

array([0.5   , 0.57  , 0.8023, 0.8071, 0.8088, 0.8106])

In [20]:
test_scores_log_reg.mean(axis=1).round(4)

array([0.5   , 0.5581, 0.7981, 0.8019, 0.8038, 0.8062])

In [21]:
log_reg=LogisticRegression(max_iter=1000, C=20)
log_reg.fit(X_train, y_train)

LogisticRegression(C=20, max_iter=1000)

In [22]:
print('log reg acc on train: {:.2%}'.format(log_reg.score(X_train, y_train)))
print('log reg acc on test: {:.2%}'.format(log_reg.score(X_test, y_test)))

log reg acc on train: 79.94%
log reg acc on test: 78.50%


In [23]:
log_reg.coef_

array([[ 1.80562301e+00,  6.58093325e-01, -2.48466435e+00,
        -1.85227806e+01, -3.48278375e+01, -3.57157720e+00,
        -8.00673043e-02,  2.90046551e-01,  1.33873194e+00,
         1.69666951e+00,  1.11453148e+00,  1.46028712e-02,
         9.83097328e-01, -9.80587826e-02,  1.42027076e+00,
         5.31704890e-01]])

In [24]:
p1=[0.2,0.4,0.5,0.1,0.4,0.3,0.2,0.5,0.2,0.5,0.5,0.2,0.2,0.4,0.5,0.2,0.1]
log_reg.predict([p1])

ValueError: X has 17 features, but LogisticRegression is expecting 16 features as input.

In [25]:
import numpy as np
np.set_printoptions(suppress=True)

In [26]:
log_reg.predict_proba([p1]).round(4)

ValueError: X has 17 features, but LogisticRegression is expecting 16 features as input.

In [27]:
log_reg.classes_

array([0, 1])

In [28]:
log_reg.coef_.round(4)

array([[  1.8056,   0.6581,  -2.4847, -18.5228, -34.8278,  -3.5716,
         -0.0801,   0.29  ,   1.3387,   1.6967,   1.1145,   0.0146,
          0.9831,  -0.0981,   1.4203,   0.5317]])

In [29]:
log_reg.intercept_.round(4)

array([9.9882])

# SVM 

In [30]:
svm1=LinearSVC(random_state=0)
svm1.fit(X_train,y_train)

LinearSVC(random_state=0)

In [31]:
svm1.coef_

array([[  1.22938622,   0.24493122,  -0.8032349 ,  -6.99867714,
        -10.02797319,  -0.5244424 ,  -0.07087926,   0.16478105,
          0.40563937,   0.46416572,   0.36308411,  -0.64152345,
          0.34479265,  -0.03438365,   1.31493451,   0.31815455]])

In [32]:
svm1.intercept_

array([1.43886974])

In [33]:
print('svm acc on train: {:.2%}'.format(svm1.score(X_train, y_train)))
print('svm acc on test: {:.2%}'.format(svm1.score(X_test, y_test)))

svm acc on train: 79.75%
svm acc on test: 78.25%


In [34]:
b=[[0.616,0.999,0.781,0.0001,0.471,0.0005,0.631,0.3696,0.0415,0.0022,0.27698,0,0.953,0,0.7022,0.0029,0.0345]]
svm1.predict(b)

ValueError: X has 17 features, but LinearSVC is expecting 16 features as input.

In [35]:
b_trns=scaler1.transform(b)
b_trns

/Users/ryanmaki/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


ValueError: X has 17 features, but MinMaxScaler is expecting 16 features as input.

In [36]:
svm1.predict((b_trns))

NameError: name 'b_trns' is not defined

In [37]:
svm1.intercept_.round(2)

array([1.44])

In [38]:
svm1.coef_.round(2)

array([[  1.23,   0.24,  -0.8 ,  -7.  , -10.03,  -0.52,  -0.07,   0.16,
          0.41,   0.46,   0.36,  -0.64,   0.34,  -0.03,   1.31,   0.32]])

In [39]:
LinearSVC()

LinearSVC()

In [40]:
C_range=[.1,1,5,10,50,100]

In [41]:
train_scores_SVM, test_scores_SVM=validation_curve(LinearSVC(random_state=0, max_iter=100000), X_bank_trns, y_bank, param_name='C',
                                           param_range=[.1,1,5,10,50,100], cv=4)

In [42]:
train_scores_SVM.round(4)

array([[0.752 , 0.7667, 0.7593, 0.7593],
       [0.7833, 0.79  , 0.7913, 0.7927],
       [0.8   , 0.8   , 0.8007, 0.804 ],
       [0.8033, 0.802 , 0.7947, 0.8   ],
       [0.81  , 0.8027, 0.7973, 0.8067],
       [0.81  , 0.8027, 0.7987, 0.8053]])

In [46]:
print('ave cross in 4 folds for different C values:')
print('training:', train_scores_SVM.mean(axis=1).round(4))
print('test', test_scores_SVM.mean(axis=1).round(4))

ave cross in 4 folds for different C values:
training: [0.7593 0.7893 0.8012 0.8    0.8042 0.8042]
test [0.7525 0.786  0.798  0.798  0.7995 0.799 ]


In [48]:
train_scores_SVM.mean()

0.7930277777777778

# Decision tree

In [49]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel, y_bank, test_size=0.2, random_state=0)

In [50]:
X_train

Continuous interest rate (after tax)   Operating Expense Rate  \
1376                               0.781566             9.310000e+09   
6215                               0.781836             1.455860e-04   
349                                0.781454             6.550000e+09   
3911                               0.781616             9.660000e+09   
5464                               0.781675             6.735830e-04   
...                                     ...                      ...   
4945                               0.781618             7.120000e+09   
3158                               0.781625             1.025700e-04   
1924                               0.781602             5.060000e+08   
3357                               0.781634             9.140000e+09   
5492                               0.781993             3.186940e-04   

       Interest-bearing debt interest rate   Net Value Per Share (A)  \
1376                              0.000267                  0.177279   
6215                              0.000000                  0.261304   
349                               0.000201                  0.153639   
3911                              0.000826                  0.177110   
5464                              0.000000                  0.180397   
...                                    ...                       ...   
4945                              0.000927                  0.207829   
3158                              0.000647                  0.178838   
1924                              0.000481                  0.193039   
3357                              0.000206                  0.174835   
5492                              0.000188                  0.201761   

       Persistent EPS in the Last Four Seasons   Operating Profit Growth Rate  \
1376                                  0.214900                       0.848122   
6215                                  0.284202                       0.848040   
349                                   0.186064                       0.848017   
3911                                  0.223598                       0.848026   
5464                                  0.229744                       0.848096   
...                                        ...                            ...   
4945                                  0.237024                       0.850289   
3158                                  0.223787                       0.848022   
1924                                  0.221802                       0.848050   
3357                                  0.219438                       0.848161   
5492                                  0.248275                       0.848070   

       Total Asset Growth Rate   Quick Ratio   Interest Expense Ratio  \
1376              8.880000e+09      0.005079                 0.633328   
6215              7.410000e+09      0.012941                 0.630617   
349               6.530000e+09      0.006014                 0.630282   
3911              7.590000e+09      0.004494                 0.631522   
5464              6.830000e+09      0.009013                 0.630612   
...                        ...           ...                      ...   
4945              8.150000e+09      0.005253                 0.631644   
3158              7.240000e+09      0.002789                 0.632245   
1924              6.790000e+08      0.002089                 0.633201   
3357              6.980000e+09      0.007633                 0.630861   
5492              6.110000e+09      0.005213                 0.630670   

       Total debt/Total net worth   Accounts Receivable Turnover  \
1376                     0.021935                       0.000706   
6215                     0.003169                       0.000611   
349                      0.026291                       0.000812   
3911                     0.006069                       0.001485   
5464                     0.002608                       0.001321   
...                

In [51]:
train_scores_decision_tree, test_scores_decision_tree=validation_curve(DecisionTreeClassifier(random_state=0), X_train, y_train, param_name='max_leaf_nodes', 
                                          param_range=[2,6,8,10,15,25,50], cv=5)

In [52]:
dt0=DecisionTreeClassifier(random_state=0, max_leaf_nodes=10)
dt0.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [53]:
print('dt0 acc on train: {:.2%}'.format(dt0.score(X_train, y_train)))
print('dt0 acc on test: {:.2%}'.format(dt0.score(X_test, y_test)))

dt0 acc on train: 91.81%
dt0 acc on test: 86.25%


In [54]:
p1=[0.616,0.999,0.781,0.0001,0.471,0.0005,0.631,0.3696,0.0415,0.0022,0.27698,0,0.953,0,0.7022,0.0029,0.0345]
dt0.predict([p1])

/Users/ryanmaki/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


ValueError: X has 17 features, but DecisionTreeClassifier is expecting 16 features as input.

In [55]:
export_graphviz(dt0, out_file='dt0_vis.dot', feature_names=X_bank_sel.columns, class_names=dt0.classes_.astype(str), impurity=False, filled=True)

In [56]:
dt0.classes_

array([0, 1])

In [57]:
dt0.feature_importances_.round(3)

array([0.166, 0.   , 0.077, 0.   , 0.086, 0.   , 0.024, 0.   , 0.   ,
       0.581, 0.   , 0.022, 0.   , 0.   , 0.023, 0.022])

In [58]:
X_bank_sel.columns

Index([' Continuous interest rate (after tax)', ' Operating Expense Rate',
       ' Interest-bearing debt interest rate', ' Net Value Per Share (A)',
       ' Persistent EPS in the Last Four Seasons',
       ' Operating Profit Growth Rate', ' Total Asset Growth Rate',
       ' Quick Ratio', ' Interest Expense Ratio',
       ' Total debt/Total net worth', ' Accounts Receivable Turnover',
       ' Operating profit per person', ' Allocation rate per person',
       ' Cash Turnover Rate', ' Cash Flow to Sales',
       ' Interest Coverage Ratio (Interest expense to EBIT)'],
      dtype='object')

In [59]:
feat_imp=pd.DataFrame(data=dt0.feature_importances_.round(3),index=X_bank_sel.columns, columns=['importance'])
feat_imp.sort_values('importance', ascending=False)

importance
 Total debt/Total net worth                              0.581
 Continuous interest rate (after tax)                    0.166
 Persistent EPS in the Last Four Seasons                 0.086
 Interest-bearing debt interest rate                     0.077
 Total Asset Growth Rate                                 0.024
 Cash Flow to Sales                                      0.023
 Operating profit per person                             0.022
 Interest Coverage Ratio (Interest expense to E...       0.022
 Operating Expense Rate                                  0.000
 Net Value Per Share (A)                                 0.000
 Operating Profit Growth Rate                            0.000
 Quick Ratio                                             0.000
 Interest Expense Ratio                                  0.000
 Accounts Receivable Turnover                            0.000
 Allocation rate per person                              0.000
 Cash Turnover Rate                                      0.000

# KNN Classifier

In [60]:
train_scores_KNN, test_scores_KNN=validation_curve(KNeighborsClassifier(), X_bank_trns, y_bank, param_name='n_neighbors', 
                                           param_range=[1,2,3,4,5,6], cv=4)

In [61]:
train_scores_KNN.mean(axis=1)

array([1.        , 0.99      , 0.94016667, 0.92966667, 0.897     ,
       0.886     ])

In [62]:
train_scores_KNN.mean()

0.9404722222222223

In [63]:
test_scores_KNN.mean()

0.8690000000000001

In [64]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel,y_bank,
                                                  random_state=0)

In [65]:
knn_cls_bank_bal=KNeighborsClassifier(n_neighbors=5)

In [66]:
knn_cls_bank_bal.fit(X_train,y_train)

KNeighborsClassifier()

In [67]:
print('knn_cls_bank_bal acc on train: {:.2%}'.format(knn_cls_bank_bal.score(X_train,y_train)))
print('knn_cls_bank_bal acc on test: {:.2%}'.format(knn_cls_bank_bal.score(X_test,y_test)),'\n')

knn_cls_bank_bal acc on train: 85.67%
knn_cls_bank_bal acc on test: 73.40% 



In [68]:
knn_cls_bank_bal.score(X_bank_sel,y_bank)

0.826

In [69]:
w1=[1,1,0.5,0.4,0.3,0.3,0.6,0.7,1,0.4,0.2,0.5,0.7,0.4,0.1,0.9,0.6]
knn_cls_bank_bal.predict([w1])

/Users/ryanmaki/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


ValueError: X has 17 features, but KNeighborsClassifier is expecting 16 features as input.

In [70]:
knn_cls_bank_bal.predict(X_bank_sel)

array([1, 0, 1, ..., 1, 0, 1])

In [71]:
len(knn_cls_bank_bal.predict(X_bank_sel))

2000

In [72]:
predict_array = knn_cls_bank_bal.predict(X_bank_sel)
count_non_zero = 0
for i in predict_array:
    if i != 0:
        count_non_zero += 1
print(count_non_zero)      

1198


# Fair Evaluation 

In [73]:
print('initial features set size:',X_bank_sel.shape)
print('X_train shape',X_train.shape)
print('X_test shape',X_test.shape)

print('y_train shape',y_train.shape)
print('y_test shape',y_test.shape)

initial features set size: (2000, 16)
X_train shape (1500, 16)
X_test shape (500, 16)
y_train shape (1500,)
y_test shape (500,)


In [74]:
knn_cls_bank_bal=KNeighborsClassifier(n_neighbors=5)

In [75]:
knn_cls_bank_bal.fit(X_train, y_train)

KNeighborsClassifier()

In [76]:
print('knn accuracy on training data:', knn_cls_bank_bal.score(X_train, y_train))
print('knn accuracy on test data:', knn_cls_bank_bal.score(X_test, y_test))

knn accuracy on training data: 0.8566666666666667
knn accuracy on test data: 0.734


# Cross-Validation

In [77]:
knn_cls_bank_bal1=KNeighborsClassifier(n_neighbors=9)

In [78]:
scores=cross_val_score(knn_cls_bank_bal1,X_bank_sel,y_bank,cv=6)
scores

array([0.76946108, 0.70359281, 0.72072072, 0.72372372, 0.67567568,
       0.69369369])

In [79]:
scores.mean()

0.7144779510048972

In [80]:
print('Average test accuracy in a 6-fold cross val is: {:.2%}'.format(
    scores.mean()))

Average test accuracy in a 6-fold cross val is: 71.45%


# Overfit and Underfit

In [81]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel, y_bank, random_state=0, test_size=0.25)

In [82]:
knn1=KNeighborsClassifier(n_neighbors=1)
knn5=KNeighborsClassifier(n_neighbors=5)
knn9=KNeighborsClassifier(n_neighbors=9)
knn29=KNeighborsClassifier(n_neighbors=29)

In [83]:
knn1.fit(X_train, y_train)
knn5.fit(X_train, y_train)
knn9.fit(X_train, y_train)
knn29.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=29)

In [84]:
print('knn1 acc on train: {:.2%}'.format(knn1.score(X_train, y_train)))
print('knn1 acc on test: {:.2%}'.format(knn1.score(X_test, y_test)),'\n')

print('knn5 acc on train: {:.2%}'.format(knn5.score(X_train, y_train)))
print('knn5 acc on test: {:.2%}'.format(knn5.score(X_test, y_test)),'\n')

print('knn9 acc on train: {:.2%}'.format(knn9.score(X_train, y_train)))
print('knn9 acc on test: {:.2%}'.format(knn9.score(X_test, y_test)),'\n')

print('knn29 acc on train: {:.2%}'.format(knn29.score(X_train, y_train)))
print('knn29 acc on test: {:.2%}'.format(knn29.score(X_test, y_test)))

knn1 acc on train: 99.67%
knn1 acc on test: 92.80% 

knn5 acc on train: 85.67%
knn5 acc on test: 73.40% 

knn9 acc on train: 78.80%
knn9 acc on test: 67.80% 

knn29 acc on train: 73.40%
knn29 acc on test: 69.20%
