# Python Packages

## NumPy

In [1]:
#importing numpy
import numpy as np

In [8]:
# create a 1-dim array
a1=np.array([22,54,0,-2,54])
a1

array([22, 54,  0, -2, 54])

In [9]:
# type coerrsion
a2=np.array([20,False,'Hi'])
a2

array(['20', 'False', 'Hi'], dtype='<U21')

In [14]:
# 2- dim array
a3=np.array([[1,4,-5,200,0], [400,5,2,0,1], [4,4,4,4,4]])
a3

array([[  1,   4,  -5, 200,   0],
       [400,   5,   2,   0,   1],
       [  4,   4,   4,   4,   4]])

In [15]:
# the shape (or size) of an array
a3.shape

(3, 5)

In [16]:
# transpose of an array
a3.T

array([[  1, 400,   4],
       [  4,   5,   4],
       [ -5,   2,   4],
       [200,   0,   4],
       [  0,   1,   4]])

In [17]:
a3.T.shape

(5, 3)

In [32]:
# How to specify a seed
np.random.seed(0)
np.random.randint(0,10,2)

array([5, 0])

In [33]:
np.random.seed(0)
a4=np.array([np.random.randint(-100,200,15),np.random.randint(-200,75,15)])
a4

array([[  72,  -53,   17,   92,  151,   95,  -91,  111,  177,  142,  192,
         -13,  -30,  -12,   93],
       [-161, -113,  -26, -112,  -35, -175, -128,   65,  -85,   43,   -3,
        -101,  -23,   43,  -53]])

In [35]:
# finding maximum value within an array
np.max(a4)

192

In [36]:
# index of maximum value
np.argmax(a4)

10

In [38]:
#finidng minimum value within an array
print('Minimum value in a4 is:', np.min(a4))
print('The index for min value in a4 is:',np.argmin(a4))

Minimum value in a4 is: -175
The index for min value in a4 is: 20


In [46]:
#standard deviation
round(np.std(a4),2)

99.34

In [34]:
#creating an array from a list
l1=[[11,2,5,7,99], [6,4,4,0,90], [1,0,0,0,32]]
a5=np.array(l1)
a5

array([[11,  2,  5,  7, 99],
       [ 6,  4,  4,  0, 90],
       [ 1,  0,  0,  0, 32]])

## Pandas

In [49]:
import pandas as pd

In [50]:
# create a list of sports
sports=['Football', 'Soccer', 'Taekwondo']
sports

['Football', 'Soccer', 'Taekwondo']

### Series

In [51]:
# create a pandas Series using the list
s1=pd.Series(sports)
s1

0     Football
1       Soccer
2    Taekwondo
dtype: object

In [53]:
# create a dictionary of sports
d_sports={'US':'Football','Argentina':'Soccer','South Korea':'Taekwondo'}
d_sports

{'US': 'Football', 'Argentina': 'Soccer', 'South Korea': 'Taekwondo'}

In [54]:
s2=pd.Series(d_sports)
s2

US              Football
Argentina         Soccer
South Korea    Taekwondo
dtype: object

In [67]:
s3 = pd.Series(data=['Football', 'Soccer', 'Taekwondo'], index=['US', 'Argentina', "South Korea"])
s3

US              Football
Argentina         Soccer
South Korea    Taekwondo
dtype: object

### Subset or retrieve values from Series 

In [59]:
# subsetting using integer index
# get the sport for the second country in Series
s3.iloc[1]

'Soccer'

In [60]:
# subset using index labels
# get the sport for the US
s3.loc['US']

'Football'

In [69]:
# Updating values in Series
# change the sport for US to basketball
s3.loc['US']='Basketball'
s3

US             Basketball
Argentina          Soccer
South Korea     badminton
dtype: object

In [68]:
# change the sport for the last country to 'badminton'
s3.iloc[-1]='badminton'
s3

US              Football
Argentina         Soccer
South Korea    badminton
dtype: object

In [72]:
# rename index labels
# if we want to make the change permanent, set the inplace to True
s3.rename(index={'Argentina':'Brazil'}, inplace=True)
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
dtype: object

In [82]:
# when adding values, we use loc with a new label
s3.loc['Canada']='Hockey'
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
UK                Fencing
China            PingPong
Switzerland        Skiing
Germany              Beer
Canada             Hockey
dtype: object

In [83]:
s3.loc['UK']='Fencing'
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
UK                Fencing
China            PingPong
Switzerland        Skiing
Germany              Beer
Canada             Hockey
dtype: object

In [75]:
s3.loc['China']='PingPong'
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
Canada             Hockey
UK                Fencing
China            PingPong
dtype: object

In [84]:
s3.loc['Switzerland']='Skiing'
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
UK                Fencing
China            PingPong
Switzerland        Skiing
Germany              Beer
Canada             Hockey
dtype: object

In [85]:
s3.loc['Germany']='Beer'
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
UK                Fencing
China            PingPong
Switzerland        Skiing
Germany              Beer
Canada             Hockey
dtype: object

In [86]:
# drop values from our Series
s3.drop('Canada', inplace=True)

In [87]:
s3

US             Basketball
Brazil             Soccer
South Korea     badminton
UK                Fencing
China            PingPong
Switzerland        Skiing
Germany              Beer
dtype: object

### DataFrames

In [93]:
df=pd.DataFrame(data={'Product':['Milk','Bread','Beer'],'Unit Price':[5,6,15]},
               index=['pr1','pr2','pr3'])
df

Product  Unit Price
pr1    Milk           5
pr2   Bread           6
pr3    Beer          15

In [99]:
sports_df=pd.DataFrame(s3,columns=['popular_sport'])
sports_df

popular_sport
US             Basketball
Brazil             Soccer
South Korea     badminton
UK                Fencing
China            PingPong
Switzerland        Skiing
Germany              Beer

In [101]:
sports_df.reset_index()

index popular_sport
0           US    Basketball
1       Brazil        Soccer
2  South Korea     badminton
3           UK       Fencing
4        China      PingPong
5  Switzerland        Skiing
6      Germany          Beer