# Import Packages

In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Linear Regression

In [31]:
#reading Boston housing data v2 -- make sure to read version 2!!!
boston2 = pd.read_csv('boston_housing_data_v2-1.csv')
boston2.head(3)

target_medv     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0         24.0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1         21.6  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2         33.4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   

   ...     col40     col41     col42     col43     col44     col45  col46  \
0  ...  0.065486  0.000000  0.084749  0.201987  0.181807  0.099108    0.0   
1  ...  0.018142  0.007515  0.060314  0.135281  0.094716  0.029873    0.0   
2  ...  0.018142  0.007515  0.060314  0.103597  0.120017  0.029873    0.0   

   col47  col48  col49  
0    0.0    0.0    0.0  
1    0.0    0.0    0.0  
2    0.0    0.0    0.0  

[3 rows x 62 columns]

In [32]:
# we ave too many columns (62) relative to the number of recors in this dataset
boston2.shape

(333, 62)

In [33]:
# create features and target sets
x_boston2, y_boston2 = boston2.iloc[:,1:], boston2['target_medv']
# check my work
display(x_boston2.head(3))
display(y_boston2.head(3))

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ...  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296  ...   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242  ...   
2  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222  ...   

      col40     col41     col42     col43     col44     col45  col46  col47  \
0  0.065486  0.000000  0.084749  0.201987  0.181807  0.099108    0.0    0.0   
1  0.018142  0.007515  0.060314  0.135281  0.094716  0.029873    0.0    0.0   
2  0.018142  0.007515  0.060314  0.103597  0.120017  0.029873    0.0    0.0   

   col48  col49  
0    0.0    0.0  
1    0.0    0.0  
2    0.0    0.0  

[3 rows x 61 columns]

0    24.0
1    21.6
2    33.4
Name: target_medv, dtype: float64

In [34]:
# split data to train and test (75/25)
x_train, x_test, y_train, y_test = train_test_split(x_boston2, y_boston2, random_state=0, test_size=.25)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(249, 61)
(84, 61)
(249,)
(84,)


In [35]:
# define the model
lr = LinearRegression()
# fit the model
lr.fit(x_train, y_train)

LinearRegression()

In [36]:
# evaluate the model's performance
print('lr R2 on train:{:.2%}'.format(lr.score(x_train, y_train)))
print('lr R2 on test:{:.2%}'.format(lr.score(x_test, y_test)))

lr R2 on train:78.94%
lr R2 on test:60.73%


# Ridge Regression

In [37]:
from sklearn.linear_model import Ridge

In [38]:
# define the model (with default perameters) -- alpha is 1 by default
ridge = Ridge()
# fit the model
ridge.fit(x_train, y_train)

Ridge()

In [39]:
# ridge model coefficients
ridge.coef_

array([-0.15083518,  0.03506091,  0.07059383,  3.57834392, -6.40759591,
        3.28455384, -0.00239048, -1.12103983,  0.33639372, -0.01510789,
       -0.53873313, -0.72401055, -0.21547832,  0.83863566, -1.17521021,
       -1.61933019,  1.55118512, -0.08421433,  0.97222014,  0.73573716,
        0.79235092,  0.39013132,  0.45172906,  0.91391948,  0.45044399,
        0.49787854,  0.27174819, -0.94219309,  0.24782388,  1.21196962,
        0.99109483,  1.96563879,  3.7158126 ,  0.76821883,  0.94133303,
        1.71261564,  1.01060253, -0.85018896,  0.2860957 , -1.47473913,
       -0.1674865 , -0.10845684,  0.66969625, -0.28687709, -0.0528973 ,
       -0.23227452,  0.31927661,  1.43029845,  2.50800571,  1.01465776,
        0.98243765,  0.63901699, -0.11765648, -1.4123672 , -0.23148077,
       -0.21786397,  2.81834691,  3.47530042, -0.65523441, -3.93394334,
        0.91688331])

In [40]:
# force the numbers oto be down in float format
import numpy as np
np.set_printoptions(suppress=True)

In [41]:
#ridge model coefficients
ridge.coef_.round(2)

array([-0.15,  0.04,  0.07,  3.58, -6.41,  3.28, -0.  , -1.12,  0.34,
       -0.02, -0.54, -0.72, -0.22,  0.84, -1.18, -1.62,  1.55, -0.08,
        0.97,  0.74,  0.79,  0.39,  0.45,  0.91,  0.45,  0.5 ,  0.27,
       -0.94,  0.25,  1.21,  0.99,  1.97,  3.72,  0.77,  0.94,  1.71,
        1.01, -0.85,  0.29, -1.47, -0.17, -0.11,  0.67, -0.29, -0.05,
       -0.23,  0.32,  1.43,  2.51,  1.01,  0.98,  0.64, -0.12, -1.41,
       -0.23, -0.22,  2.82,  3.48, -0.66, -3.93,  0.92])

In [42]:
lr.coef_.round(2)

array([ -0.11,   0.01,   0.06,   4.84, -25.05,   3.42,   0.01,  -1.14,
         0.36,  -0.01,  -0.6 ,  -0.7 ,  -0.65,  14.55, -22.33, -24.49,
        15.19,  -6.11,  -4.3 ,  22.73,  -0.45, -24.74,  15.54,  26.07,
       -79.91, -75.28,  15.8 ,  -6.75, -16.33,   3.65,  27.97,  99.37,
        30.77,   5.93,   1.59,  10.38,  53.85, -30.95, -13.78,   1.8 ,
        -2.63,  26.52,   0.24, -24.99, -37.38, -36.57,   0.88,  -0.98,
         0.51,  -7.83,  19.75, -75.05, 148.61, -17.63, -61.48,   8.36,
        44.94,  12.53,   9.85, -24.09, -13.37])

In [43]:
# 52 coefficents have smaller absolute value in ridge compared to linear regression model
sum(abs(ridge.coef_)<=abs(lr.coef_))

52

In [44]:
# evaluate ridge's performance
print('ridge R2 on train:{:.2%}'.format(ridge.score(x_train,y_train)))
print('ridge R2 on test:{:.2%}'.format(ridge.score(x_test,y_test)))

ridge R2 on train:75.19%
ridge R2 on test:68.49%


## Adjusting Alpha

In [45]:
# Adjust alpha to control the complexity of the ridge model
# Ridge(alpha = 0) ------------------ Regular linear regression model (most complex)
# smaller alpha -- more complex model/higher chance of overfitting
ridge1 = Ridge(alpha = .01)

# in between
ridge2 = Ridge(alpha = 1)

# larger alpha -- less complex (simpler) model/lower chance of over-fitting 
# if we keep increading alpha we may do underfitting eventually (very simple model)
ridge3 = Ridge(alpha = 10)

In [46]:
# fit the models 
ridge1.fit(x_train, y_train)
ridge2.fit(x_train, y_train)
ridge3.fit(x_train, y_train)

Ridge(alpha=10)

In [47]:
# evaluate performance 
print('ridge1 R2 score on train: {:.2%}'.format(ridge1.score(x_train, y_train)))
print('ridge1 R2 score on test: {:.2%}'.format(ridge1.score(x_test, y_test)), '\n')

print('ridge2 R2 score on train: {:.2%}'.format(ridge2.score(x_train, y_train)))
print('ridge2 R2 score on test: {:.2%}'.format(ridge2.score(x_test, y_test)), '\n')

print('ridge3 R2 score on train: {:.2%}'.format(ridge3.score(x_train, y_train)))
print('ridge3 R2 score on test: {:.2%}'.format(ridge3.score(x_test, y_test)), '\n')

ridge1 R2 score on train: 78.44%
ridge1 R2 score on test: 66.67% 

ridge2 R2 score on train: 75.19%
ridge2 R2 score on test: 68.49% 

ridge3 R2 score on train: 73.62%
ridge3 R2 score on test: 68.13% 



# Lasso

In [48]:
from sklearn.linear_model import Lasso

In [49]:
# define a Lasso with default param values -- by default, alpha is 1
lasso = Lasso()
# fit the model 
lasso.fit(x_train,y_train)

Lasso()

In [50]:
# evaluate the performance
print ('lasso R2 on train:{:.2%}'.format(lasso.score(x_train,y_train)))
print ('lasso R2 on test:{:.2%}'.format(lasso.score(x_test,y_test)))

lasso R2 on train:66.06%
lasso R2 on test:60.40%


In [51]:
lasso.coef_.round(2)

array([-0.09,  0.02,  0.  ,  0.  , -0.  ,  0.68,  0.03, -0.4 ,  0.26,
       -0.01, -0.53, -0.9 ,  0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
       -0.  , -0.  , -0.  , -0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  , -0.  ,  0.  ,  0.  , -0.  , -0.  ,  0.  , -0.  ,
       -0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ,
        0.  ,  0.  ,  0.  ,  0.  , -0.  , -0.  ,  0.  ])

In [52]:
# number of non-0 coefficients 
sum(lasso.coef_ != 0)

9

## Adjusting Alpha

In [54]:
# Lasso (alpha=0) -- regular linear regression

#smaller alpha -- more complex complex model -- higher chancve of overfitting
lasso1 = Lasso(alpha=.0001, max_iter=100000)

# in between
lasso2 = Lasso(alpha=.001, max_iter=100000)

# in between
lasso3 = Lasso(alpha=.1, max_iter=100000)

# larger alpha -- less complex (simpler) -- lower chance of overfitting but can have underfitting (too simple)
lasso4 = Lasso(alpha=1, max_iter=100000)

Lasso(alpha=0.0001, max_iter=100000)

Lasso(alpha=0.001, max_iter=100000)

Lasso(alpha=0.1, max_iter=100000)

Lasso(alpha=1, max_iter=100000)

In [55]:
# fit all models
lasso1.fit(x_train, y_train)
lasso2.fit(x_train, y_train)
lasso3.fit(x_train, y_train)
lasso4.fit(x_train, y_train)

Lasso(alpha=1, max_iter=100000)

In [62]:
# evaluate their performance
#find the number of non-zero coeffs
# choose the best model

print('lasso1 R2 score on train: {:.2%}'.format(lasso1.score(x_train, y_train)))
print('lasso1 R2 score on test: {:.2%}'.format(lasso1.score(x_test, y_test)))
print('lasso1 # of non-zero coeffs:', sum(lasso1.coef_ != 0), '\n')

print('lasso2 R2 score on train: {:.2%}'.format(lasso2.score(x_train, y_train)))
print('lasso R2 score on test: {:.2%}'.format(lasso2.score(x_test, y_test)))
print('lasso2 # of non-zero coeffs:', sum(lasso2.coef_ != 0), '\n')

print('lasso3 R2 score on train: {:.2%}'.format(lasso3.score(x_train, y_train)))
print('lasso3 R2 score on test: {:.2%}'.format(lasso3.score(x_test, y_test)))
print('lasso3 # of non-zero coeffs:', sum(lasso3.coef_ != 0), '\n')

print('lasso4 R2 score on train: {:.2%}'.format(lasso4.score(x_train, y_train)))
print('lasso4 R2 score on test: {:.2%}'.format(lasso4.score(x_test, y_test)))
print('lasso4 # of non-zero coeffs:', sum(lasso4.coef_ != 0), '\n')

lasso1 R2 score on train: 78.93%
lasso1 R2 score on test: 62.31%
lasso1 # of non-zero coeffs: 57 

lasso2 R2 score on train: 78.27%
lasso R2 score on test: 68.07%
lasso2 # of non-zero coeffs: 49 

lasso3 R2 score on train: 72.48%
lasso3 R2 score on test: 66.94%
lasso3 # of non-zero coeffs: 14 

lasso4 R2 score on train: 66.06%
lasso4 R2 score on test: 60.40%
lasso4 # of non-zero coeffs: 9 



In [63]:
# lasso 2 or 3 is best depending on the case (if you want a simpler model then use lasso 3, if you want 
# it to be more accurate, use lasso 2)