# boston housing data v2 (version 2)

## provided code

In [41]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [42]:
# reading the data (boston_housing_data_v2)
boston2=pd.read_csv('boston_housing_data_v2-1.csv')
boston2.head(2)

target_medv     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0         24.0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1         21.6  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   

   ...     col40     col41     col42     col43     col44     col45  col46  \
0  ...  0.065486  0.000000  0.084749  0.201987  0.181807  0.099108    0.0   
1  ...  0.018142  0.007515  0.060314  0.135281  0.094716  0.029873    0.0   

   col47  col48  col49  
0    0.0    0.0    0.0  
1    0.0    0.0    0.0  

[2 rows x 62 columns]

In [43]:
# creating features and target sets
x_boston, y_boston=boston2.iloc[:,1:], boston2['target_medv']
x_boston.head(2)

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ...  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296  ...   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242  ...   

      col40     col41     col42     col43     col44     col45  col46  col47  \
0  0.065486  0.000000  0.084749  0.201987  0.181807  0.099108    0.0    0.0   
1  0.018142  0.007515  0.060314  0.135281  0.094716  0.029873    0.0    0.0   

   col48  col49  
0    0.0    0.0  
1    0.0    0.0  

[2 rows x 61 columns]

In [44]:
# split to train and test
x_train, x_test, y_train, y_test=train_test_split(x_boston, y_boston, random_state=88)

## you part

In [45]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(249, 61)
(84, 61)
(249,)
(84,)


In [46]:
from sklearn.linear_model import LinearRegression
# define the model
lr = LinearRegression()
# fit the model
lr.fit(x_train, y_train)

LinearRegression()

In [47]:
# evaluate the model's performance
print('lr R2 on train: {:.2%}'.format(lr.score(x_train, y_train)))
print('lr R2 on test: {:.2%}'.format(lr.score(x_test, y_test)))

lr R2 on train: 80.11%
lr R2 on test: 59.16%


In [48]:
from sklearn.linear_model import Ridge

In [49]:
from sklearn.linear_model import Lasso

In [50]:
# define the model (with default perameters) -- alpha is 1 by default
ridge = Ridge()
# fit the model
ridge.fit(x_train, y_train)

Ridge()

In [51]:
# ridge model coefficients
ridge.coef_

array([-0.11942002,  0.07026909, -0.01444316,  3.04522878, -7.68886306,
        3.25619341,  0.00093144, -1.65077744,  0.42601293, -0.01748805,
       -0.76360666, -0.65633283,  0.81839263,  1.81448902, -2.70643186,
        0.41204264,  0.94506179, -0.32390358,  0.61188494,  1.5077661 ,
       -0.38235833, -0.64607565,  1.01969465,  2.31174101,  1.27165287,
        0.90458581,  0.73751918,  1.85142133, -0.46464676,  2.04637209,
        2.14634912,  2.77196099,  3.35180798,  0.69941559,  1.44072227,
        0.26026375, -0.1514385 , -0.32685775,  1.71432754, -2.53230964,
        0.7121408 , -1.11922171,  0.4591097 ,  0.93027855,  0.96372039,
       -1.1051396 ,  1.26486033,  0.04723196,  0.23051394,  1.32296335,
        0.91495732,  0.40883903,  0.23116632, -0.29932818, -0.00397597,
        1.12976888,  1.13425589,  3.47142479, -1.30830282, -4.34056626,
        1.7606089 ])

In [52]:
# force the numbers oto be down in float format
import numpy as np
np.set_printoptions(suppress=True)

In [53]:
#ridge model coefficients
ridge.coef_.round(2)

array([-0.12,  0.07, -0.01,  3.05, -7.69,  3.26,  0.  , -1.65,  0.43,
       -0.02, -0.76, -0.66,  0.82,  1.81, -2.71,  0.41,  0.95, -0.32,
        0.61,  1.51, -0.38, -0.65,  1.02,  2.31,  1.27,  0.9 ,  0.74,
        1.85, -0.46,  2.05,  2.15,  2.77,  3.35,  0.7 ,  1.44,  0.26,
       -0.15, -0.33,  1.71, -2.53,  0.71, -1.12,  0.46,  0.93,  0.96,
       -1.11,  1.26,  0.05,  0.23,  1.32,  0.91,  0.41,  0.23, -0.3 ,
       -0.  ,  1.13,  1.13,  3.47, -1.31, -4.34,  1.76])

In [54]:
lr.coef_.round(2)

array([ -0.07,   0.04,   0.02,   4.11, -23.71,   3.45,   0.  ,  -1.78,
         0.37,  -0.01,  -0.9 ,  -0.67,  -1.74,  15.12,  -2.71, -24.01,
         2.03,   2.3 ,  25.56,  31.19, -13.49, -91.78,  26.51, -45.38,
       -47.53,  34.78, -20.22,  22.36, -71.66,   1.19,  67.28, 121.6 ,
        48.58,  20.57,  -4.22,  12.49,  -8.7 , -16.71,   8.41, -21.37,
       -26.14,  20.31,   7.82, -24.38,  21.22,  -5.6 ,  17.94, -17.31,
       -27.13, -13.91,   6.08,  66.71, 130.5 , -58.84,  20.63,  -2.31,
       -35.92,   9.75,   5.76, -20.59,  -2.52])

In [55]:
# 52 coefficents have smaller absolute value in ridge compared to linear regression model
sum(abs(ridge.coef_)<=abs(lr.coef_))

56

In [56]:
# evaluate ridge's performance
print('ridge R2 on train:{:.2%}'.format(ridge.score(x_train,y_train)))
print('ridge R2 on test:{:.2%}'.format(ridge.score(x_test,y_test)))

ridge R2 on train:75.60%
ridge R2 on test:68.79%


In [57]:
# Adjust alpha to control the complexity of the ridge model
# Ridge(alpha = 0) ------------------ Regular linear regression model (most complex)
# smaller alpha -- more complex model/higher chance of overfitting
ridge1 = Ridge(alpha = .01)

# in between
ridge2 = Ridge(alpha = 1)

# larger alpha -- less complex (simpler) model/lower chance of over-fitting 
# if we keep increading alpha we may do underfitting eventually (very simple model)
ridge3 = Ridge(alpha = 10)

In [58]:
# fit the models 
ridge1.fit(x_train, y_train)
ridge2.fit(x_train, y_train)
ridge3.fit(x_train, y_train)

Ridge(alpha=10)

In [59]:
# evaluate performance 
print('ridge1 R2 score on train: {:.2%}'.format(ridge1.score(x_train, y_train)))
print('ridge1 R2 score on test: {:.2%}'.format(ridge1.score(x_test, y_test)), '\n')

print('ridge2 R2 score on train: {:.2%}'.format(ridge2.score(x_train, y_train)))
print('ridge2 R2 score on test: {:.2%}'.format(ridge2.score(x_test, y_test)), '\n')

print('ridge3 R2 score on train: {:.2%}'.format(ridge3.score(x_train, y_train)))
print('ridge3 R2 score on test: {:.2%}'.format(ridge3.score(x_test, y_test)), '\n')

ridge1 R2 score on train: 79.50%
ridge1 R2 score on test: 63.57% 

ridge2 R2 score on train: 75.60%
ridge2 R2 score on test: 68.79% 

ridge3 R2 score on train: 73.58%
ridge3 R2 score on test: 69.32% 



In [60]:
# define a Lasso with default param values -- by default, alpha is 1
lasso = Lasso()
# fit the model 
lasso.fit(x_train,y_train)

Lasso()

In [61]:
print ('lasso R2 on train:{:.2%}'.format(lasso.score(x_train,y_train)))
print ('lasso R2 on test:{:.2%}'.format(lasso.score(x_test,y_test)))

lasso R2 on train:65.93%
lasso R2 on test:60.53%


In [62]:
lasso.coef_.round(2)

array([-0.08,  0.07, -0.  ,  0.  , -0.  ,  0.1 ,  0.05, -0.56,  0.38,
       -0.02, -0.67, -0.89,  0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  , -0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  , -0.  ,  0.  ,  0.  , -0.  , -0.  ,  0.  , -0.  ,
       -0.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.  ,
        0.  ,  0.  ,  0.  ,  0.  , -0.  , -0.  ,  0.  ])

In [63]:
# number of non-0 coefficients 
sum(lasso.coef_ != 0)

9

In [64]:
# Lasso (alpha=0) -- regular linear regression

#smaller alpha -- more complex complex model -- higher chancve of overfitting
lasso1 = Lasso(alpha=.0001, max_iter=100000)

# in between
lasso2 = Lasso(alpha=.001, max_iter=100000)

# in between
lasso3 = Lasso(alpha=.1, max_iter=100000)

# larger alpha -- less complex (simpler) -- lower chance of overfitting but can have underfitting (too simple)
lasso4 = Lasso(alpha=1, max_iter=100000)

# largest alpha -- less complex (simpler) -- lower chance of overfitting but can have underfitting (too simple)
lasso5 = Lasso(alpha=2, max_iter=100000)

In [65]:
# fit all models
lasso1.fit(x_train, y_train)
lasso2.fit(x_train, y_train)
lasso3.fit(x_train, y_train)
lasso4.fit(x_train, y_train)
lasso5.fit(x_train, y_train)

Lasso(alpha=2, max_iter=100000)

In [66]:
# evaluate their performance
#find the number of non-zero coeffs
# choose the best model

print('lasso1 R2 score on train: {:.2%}'.format(lasso1.score(x_train, y_train)))
print('lasso1 R2 score on test: {:.2%}'.format(lasso1.score(x_test, y_test)))
print('lasso1 # of non-zero coeffs:', sum(lasso1.coef_ != 0), '\n')

print('lasso2 R2 score on train: {:.2%}'.format(lasso2.score(x_train, y_train)))
print('lasso R2 score on test: {:.2%}'.format(lasso2.score(x_test, y_test)))
print('lasso2 # of non-zero coeffs:', sum(lasso2.coef_ != 0), '\n')

print('lasso3 R2 score on train: {:.2%}'.format(lasso3.score(x_train, y_train)))
print('lasso3 R2 score on test: {:.2%}'.format(lasso3.score(x_test, y_test)))
print('lasso3 # of non-zero coeffs:', sum(lasso3.coef_ != 0), '\n')

print('lasso4 R2 score on train: {:.2%}'.format(lasso4.score(x_train, y_train)))
print('lasso4 R2 score on test: {:.2%}'.format(lasso4.score(x_test, y_test)))
print('lasso4 # of non-zero coeffs:', sum(lasso4.coef_ != 0), '\n')

print('lasso5 R2 score on train: {:.2%}'.format(lasso5.score(x_train, y_train)))
print('lasso5 R2 score on test: {:.2%}'.format(lasso5.score(x_test, y_test)))
print('lasso5 # of non-zero coeffs:', sum(lasso5.coef_ != 0), '\n')

lasso1 R2 score on train: 80.09%
lasso1 R2 score on test: 59.95%
lasso1 # of non-zero coeffs: 60 

lasso2 R2 score on train: 79.46%
lasso R2 score on test: 63.31%
lasso2 # of non-zero coeffs: 51 

lasso3 R2 score on train: 71.82%
lasso3 R2 score on test: 68.78%
lasso3 # of non-zero coeffs: 14 

lasso4 R2 score on train: 65.93%
lasso4 R2 score on test: 60.53%
lasso4 # of non-zero coeffs: 9 

lasso5 R2 score on train: 62.39%
lasso5 R2 score on test: 57.55%
lasso5 # of non-zero coeffs: 7 

