In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import validation_curve
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.ensemble import RandomForestClassifier

In [3]:
%pwd

'/Users/terryjiang'

In [6]:
bank_bal=pd.read_csv('data.csv.zip')
bank_bal

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0             1                                           0.370594          
1             1                                           0.464291          
2             1                                           0.426071          
3             1                                           0.399844          
4             1                                           0.465022          
...         ...                                                ...          
6814          0                                           0.493687          
6815          0                                           0.475162          
6816          0                                           0.472725          
6817          0                                           0.506264          
6818          0                                           0.493053          

       ROA(A) before interest and % after tax  \
0                                    0.424389   
1                                    0.538214   
2                                    0.499019   
3                                    0.451265   
4                                    0.538432   
...                                       ...   
6814                                 0.539468   
6815                                 0.538269   
6816                                 0.533744   
6817                                 0.559911   
6818                                 0.570105   

       ROA(B) before interest and depreciation after tax  \
0                                              0.405750    
1                                              0.516730    
2                                              0.472295    
3                                              0.457733    
4                                              0.522298    
...                                                 ...    
6814                                           0.543230    
6815                                           0.524172    
6816                                           0.520638    
6817                                           0.554045    
6818                                           0.549548    

       Operating Gross Margin   Realized Sales Gross Margin  \
0                    0.601457                      0.601457   
1                    0.610235                      0.610235   
2                    0.601450                      0.601364   
3                    0.583541                      0.583541   
4                    0.598783                      0.598783   
...                       ...                           ...   
6814                 0.604455                      0.604462   
6815                 0.598308                      0.598308   
6816                 0.610444                      0.610213   
6817                 0.607850                      0.607850   
6818                 0.627409                      0.627409   

       Operating Profit Rate   Pre-tax net Interest Rate  \
0                   0.998969                    0.796887   
1                   0.998946                    0.797380   
2                   0.998857                    0.796403   
3                   0.998700                    0.796967   
4                   0.998973                    0.797366   
...                      ...                         ...   
6814                0.998992                    0.797409   
6815                0.998992                    0.797414   
6816                0.998984                    0.797401   
6817                0.999074                    0.797500   
6818                0.998080                    0.801987   

       After-tax net Interest Rate  \
0                         0.808809   
1                         0.809301   
2                         0.808388   
3                         0.808966   
4                         0.809304   
...                            ...   
6814                      0

# Data Sampling

In [8]:
bank_bal=bank_bal.groupby('Bankrupt?',group_keys=False).apply(lambda x: x.sample(1000,replace=True,random_state=0))
bank_bal['Bankrupt?'].value_counts()

0    1000
1    1000
Name: Bankrupt?, dtype: int64

In [9]:
bank_bal

Bankrupt?   ROA(C) before interest and depreciation before interest  \
2893          0                                           0.616195          
2765          0                                           0.582850          
1731          0                                           0.500463          
3434          0                                           0.475455          
5125          0                                           0.518403          
...         ...                                                ...          
2149          1                                           0.412616          
4264          1                                           0.407400          
1752          1                                           0.448447          
2704          1                                           0.495539          
0             1                                           0.370594          

       ROA(A) before interest and % after tax  \
2893                                 0.655037   
2765                                 0.621784   
1731                                 0.545464   
3434                                 0.545464   
5125                                 0.578772   
...                                       ...   
2149                                 0.422209   
4264                                 0.442652   
1752                                 0.463694   
2704                                 0.545901   
0                                    0.424389   

       ROA(B) before interest and depreciation after tax  \
2893                                           0.642915    
2765                                           0.622196    
1731                                           0.547620    
3434                                           0.532684    
5125                                           0.562129    
...                                                 ...    
2149                                           0.453557    
4264                                           0.438086    
1752                                           0.486000    
2704                                           0.547674    
0                                              0.405750    

       Operating Gross Margin   Realized Sales Gross Margin  \
2893                 0.616325                      0.616325   
2765                 0.642586                      0.642586   
1731                 0.605198                      0.605198   
3434                 0.598661                      0.598675   
5125                 0.599158                      0.599165   
...                       ...                           ...   
2149                 0.598358                      0.598358   
4264                 0.609349                      0.609320   
1752                 0.594027                      0.594027   
2704                 0.619770                      0.619770   
0                    0.601457                      0.601457   

       Operating Profit Rate   Pre-tax net Interest Rate  \
2893                0.999192                    0.797712   
2765                0.999160                    0.797665   
1731                0.999033                    0.797413   
3434                0.998970                    0.797396   
5125                0.999015                    0.797446   
...                      ...                         ...   
2149                0.998916                    0.796831   
4264                0.998786                    0.797106   
1752                0.998887                    0.797178   
2704                0.999041                    0.797473   
0                   0.998969                    0.796887   

       After-tax net Interest Rate  \
2893                      0.809545   
2765                      0.809535   
1731                      0.809341   
3434                      0.809328   
5125                      0.809354   
...                            ...   
2149                      0

# Logistic Regression¶

In [10]:
bank_bal[bank_bal['Bankrupt?']==1].describe().round(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count     1000.0                                            1000.00          
mean         1.0                                               0.42          
std          0.0                                               0.08          
min          1.0                                               0.02          
25%          1.0                                               0.39          
50%          1.0                                               0.44          
75%          1.0                                               0.47          
max          1.0                                               0.58          

        ROA(A) before interest and % after tax  \
count                                  1000.00   
mean                                      0.45   
std                                       0.11   
min                                       0.00   
25%                                       0.43   
50%                                       0.49   
75%                                       0.53   
max                                       0.58   

        ROA(B) before interest and depreciation after tax  \
count                                            1000.00    
mean                                                0.46    
std                                                 0.09    
min                                                 0.03    
25%                                                 0.43    
50%                                                 0.49    
75%                                                 0.52    
max                                                 0.62    

        Operating Gross Margin   Realized Sales Gross Margin  \
count                  1000.00                       1000.00   
mean                      0.60                          0.60   
std                       0.01                          0.01   
min                       0.53                          0.53   
25%                       0.59                          0.59   
50%                       0.60                          0.60   
75%                       0.60                          0.60   
max                       0.67                          0.67   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count                 1000.00                     1000.00   
mean                     1.00                        0.80   
std                      0.00                        0.00   
min                      0.99                        0.76   
25%                      1.00                        0.80   
50%                      1.00                        0.80   
75%                      1.00                        0.80   
max                      1.00                        0.80   

        After-tax net Interest Rate  \
count                       1000.00   
mean                           0.81   
std                            0.01   
min                            0.76   
25%                            0.81   
50%                            0.81   
75%                            0.81   
max                            0.81   

        Non-industry income and expenditure/revenue  ...  \
count                                       1000.00  ...   
mean                                           0.30  ...   
std                                            0.01  ...   
min                                            0.24  ...   
25%                                            0.30  ...   
50%                                            0.30  ...   
75%                                            0.30  ...   
max                                            0.31  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                      1000.00                1.000000e+03   
mean                          0.73                1.276100e+08   
std                           0.09                1.012655e+09   
min                

In [11]:
bank_bal[bank_bal['Bankrupt?']==0].describe().round(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count     1000.0                                            1000.00          
mean         0.0                                               0.51          
std          0.0                                               0.06          
min          0.0                                               0.23          
25%          0.0                                               0.48          
50%          0.0                                               0.51          
75%          0.0                                               0.54          
max          0.0                                               1.00          

        ROA(A) before interest and % after tax  \
count                                  1000.00   
mean                                      0.56   
std                                       0.06   
min                                       0.16   
25%                                       0.54   
50%                                       0.56   
75%                                       0.59   
max                                       0.95   

        ROA(B) before interest and depreciation after tax  \
count                                            1000.00    
mean                                                0.56    
std                                                 0.06    
min                                                 0.21    
25%                                                 0.53    
50%                                                 0.56    
75%                                                 0.59    
max                                                 0.96    

        Operating Gross Margin   Realized Sales Gross Margin  \
count                  1000.00                       1000.00   
mean                      0.61                          0.61   
std                       0.01                          0.01   
min                       0.45                          0.45   
25%                       0.60                          0.60   
50%                       0.61                          0.61   
75%                       0.61                          0.61   
max                       0.66                          0.66   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count                 1000.00                     1000.00   
mean                     1.00                        0.80   
std                      0.00                        0.00   
min                      0.97                        0.75   
25%                      1.00                        0.80   
50%                      1.00                        0.80   
75%                      1.00                        0.80   
max                      1.00                        0.80   

        After-tax net Interest Rate  \
count                       1000.00   
mean                           0.81   
std                            0.00   
min                            0.77   
25%                            0.81   
50%                            0.81   
75%                            0.81   
max                            0.81   

        Non-industry income and expenditure/revenue  ...  \
count                                       1000.00  ...   
mean                                           0.30  ...   
std                                            0.00  ...   
min                                            0.28  ...   
25%                                            0.30  ...   
50%                                            0.30  ...   
75%                                            0.30  ...   
max                                            0.31  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                      1000.00                1.000000e+03   
mean                          0.81                1.651000e+07   
std                           0.03                3.742320e+08   
min                

## controlling the complexity of log regression, using parameter 'c'

In [12]:
X_bank, y_bank=bank_bal.iloc[:,1:], bank_bal['Bankrupt?'] 
display(X_bank.head(2))
display(y_bank.head(2))

ROA(C) before interest and depreciation before interest  \
2893                                           0.616195          
2765                                           0.582850          

       ROA(A) before interest and % after tax  \
2893                                 0.655037   
2765                                 0.621784   

       ROA(B) before interest and depreciation after tax  \
2893                                           0.642915    
2765                                           0.622196    

       Operating Gross Margin   Realized Sales Gross Margin  \
2893                 0.616325                      0.616325   
2765                 0.642586                      0.642586   

       Operating Profit Rate   Pre-tax net Interest Rate  \
2893                0.999192                    0.797712   
2765                0.999160                    0.797665   

       After-tax net Interest Rate  \
2893                      0.809545   
2765                      0.809535   

       Non-industry income and expenditure/revenue  \
2893                                      0.303622   
2765                                      0.303607   

       Continuous interest rate (after tax)  ...   Net Income to Total Assets  \
2893                               0.781821  ...                     0.861914   
2765                               0.781791  ...                     0.844453   

       Total assets to GNP price   No-credit Interval   Gross Profit to Sales  \
2893                    0.002909             0.623981                0.616320   
2765                    0.000395             0.623838                0.642585   

       Net Income to Stockholder's Equity   Liability to Equity  \
2893                             0.844897              0.278677   
2765                             0.842776              0.276194   

       Degree of Financial Leverage (DFL)  \
2893                             0.026794   
2765                             0.026802   

       Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
2893                                           0.565174                   1   
2765                                           0.565209                   1   

       Equity to Liability  
2893              0.034458  
2765              0.074229  

[2 rows x 95 columns]

2893    0
2765    0
Name: Bankrupt?, dtype: int64

## Feature Selection

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
dt=DecisionTreeClassifier(random_state=0)
dt.fit(X_bank,y_bank)

DecisionTreeClassifier(random_state=0)

In [15]:
sum(dt.feature_importances_>.01)

17

In [16]:
X_bank_sel=X_bank[X_bank.columns[dt.feature_importances_>.01]]
X_bank_sel.head()

Realized Sales Gross Margin   Operating Profit Rate  \
2893                      0.616325                0.999192   
2765                      0.642586                0.999160   
1731                      0.605198                0.999033   
3434                      0.598675                0.998970   
5125                      0.599165                0.999015   

       Continuous interest rate (after tax)   Operating Expense Rate  \
2893                               0.781821             1.414234e-04   
2765                               0.781791             5.949498e-04   
1731                               0.781601             1.217652e-04   
3434                               0.781587             8.040000e+09   
5125                               0.781616             4.290000e+09   

       Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
2893         0.471874                0.000511                 0.630626   
2765         0.474274                0.000504                 0.630653   
1731         0.461560                0.000529                 0.633266   
3434         0.461483                0.000455                 0.631264   
5125         0.471963                0.000484                 0.630827   

       Borrowing dependency   Net Worth Turnover Rate (times)  \
2893               0.369638                          0.041452   
2765               0.369884                          0.027742   
1731               0.377127                          0.024355   
3434               0.378270                          0.060484   
5125               0.378462                          0.089355   

       Allocation rate per person   Inventory/Working Capital  \
2893                     0.002231                    0.276975   
2765                     0.001130                    0.277239   
1731                     0.030132                    0.277396   
3434                     0.007349                    0.277195   
5125                     0.003401                    0.277167   

       Inventory/Current Liability   Retained Earnings to Total Assets  \
2893                      0.000000                            0.953235   
2765                      0.026619                            0.947642   
1731                      0.005834                            0.932778   
3434                      0.001691                            0.933728   
5125                      0.006017                            0.938630   

       Cash Turnover Rate   Current Liability to Liability  \
2893         1.100000e+09                         0.702181   
2765         2.700000e+09                         0.956182   
1731         6.130000e+09                         0.615365   
3434         2.910000e+09                         0.990300   
5125         9.300000e+09                         0.729870   

       Total assets to GNP price   Equity to Liability  
2893                    0.002909              0.034458  
2765                    0.000395              0.074229  
1731                    0.001395              0.028003  
3434                    0.000755              0.020906  
5125                    0.005034              0.021249

## transform the features

In [17]:
scaler1=MinMaxScaler()
X_bank_trns=scaler1.fit_transform(X_bank_sel)
X_bank_trns

array([[7.73312812e-01, 9.82548201e-01, 9.16489802e-01, ...,
        6.86644392e-01, 2.90976116e-13, 3.25008656e-02],
       [8.95238733e-01, 9.81323358e-01, 9.15889703e-01, ...,
        9.53895586e-01, 3.04361447e-14, 7.48655416e-02],
       [7.21651554e-01, 9.76494484e-01, 9.12167984e-01, ...,
        5.95299014e-01, 1.34017374e-13, 2.56255361e-02],
       ...,
       [6.69789541e-01, 9.70907793e-01, 9.06535856e-01, ...,
        6.84193412e-01, 1.58532414e-13, 1.56528592e-02],
       [7.89306387e-01, 9.76785274e-01, 9.12861677e-01, ...,
        7.69072401e-01, 2.00108797e-13, 4.66873896e-02],
       [7.04286144e-01, 9.74058017e-01, 9.00086161e-01, ...,
        6.59380527e-01, 9.44858467e-13, 1.33390400e-02]])

## validation curve functions

In [18]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_trns, y_bank, test_size=0.2, random_state=0)

In [19]:
train_scores_log_reg, test_scores_log_reg=validation_curve(LogisticRegression(penalty='l1', solver='saga', max_iter=100000), X_train, y_train, param_name='C',
                                           param_range=[0.01,0.05,1,5,10,20], cv=4)

In [20]:
train_scores_log_reg.mean(axis=1).round(4)

array([0.5   , 0.7585, 0.8235, 0.85  , 0.8529, 0.8542])

In [21]:
test_scores_log_reg.mean(axis=1).round(4)

array([0.5   , 0.7556, 0.8181, 0.8444, 0.845 , 0.8462])

In [22]:
log_reg=LogisticRegression(max_iter=1000, C=20)
log_reg.fit(X_train, y_train)

LogisticRegression(C=20, max_iter=1000)

In [23]:
print('log reg acc on train: {:.2%}'.format(log_reg.score(X_train, y_train)))
print('log reg acc on test: {:.2%}'.format(log_reg.score(X_test, y_test)))

log reg acc on train: 83.50%
log reg acc on test: 85.00%


In [24]:
log_reg.coef_

array([[-6.91663087e+00,  8.79304840e+00, -5.27932152e+00,
        -1.28199976e-02, -1.02619857e+01,  6.22985190e-01,
         2.99142714e+00,  5.95006278e+00, -1.22106913e+00,
         2.74156076e+00, -7.11789114e+00,  4.07425044e-01,
        -1.51317366e+01, -1.65845483e-01, -5.96896452e-02,
        -1.60568421e+00, -1.76186155e+01]])

In [25]:
p1=[0.2,0.4,0.5,0.1,0.4,0.3,0.2,0.5,0.2,0.5,0.5,0.2,0.2,0.4,0.5,0.2,0.1]
log_reg.predict([p1])

array([1])

In [26]:
import numpy as np
np.set_printoptions(suppress=True)

In [27]:
log_reg.predict_proba([p1]).round(4)

array([[0.0011, 0.9989]])

In [28]:
log_reg.classes_

array([0, 1])

In [29]:
log_reg.coef_.round(4)

array([[ -6.9166,   8.793 ,  -5.2793,  -0.0128, -10.262 ,   0.623 ,
          2.9914,   5.9501,  -1.2211,   2.7416,  -7.1179,   0.4074,
        -15.1317,  -0.1658,  -0.0597,  -1.6057, -17.6186]])

In [30]:
log_reg.intercept_.round(4)

array([15.2447])

# SVM 

In [31]:
X_bank_trns

array([[0.77331281, 0.9825482 , 0.9164898 , ..., 0.68664439, 0.        ,
        0.03250087],
       [0.89523873, 0.98132336, 0.9158897 , ..., 0.95389559, 0.        ,
        0.07486554],
       [0.72165155, 0.97649448, 0.91216798, ..., 0.59529901, 0.        ,
        0.02562554],
       ...,
       [0.66978954, 0.97090779, 0.90653586, ..., 0.68419341, 0.        ,
        0.01565286],
       [0.78930639, 0.97678527, 0.91286168, ..., 0.7690724 , 0.        ,
        0.04668739],
       [0.70428614, 0.97405802, 0.90008616, ..., 0.65938053, 0.        ,
        0.01333904]])

In [32]:
svm1=LinearSVC(random_state=0)
svm1.fit(X_train,y_train)

LinearSVC(random_state=0)

In [33]:
svm1.coef_

array([[-2.3922309 ,  3.02109436, -1.27422496, -0.00527948, -2.20330322,
        -0.        ,  1.20639627,  3.02475093, -0.16313754,  0.89815626,
        -1.72630618,  0.0456347 , -5.17381964, -0.04322548, -0.00509823,
        -0.56900942, -3.13605435]])

In [34]:
svm1.intercept_

array([3.50851562])

In [35]:
print('svm acc on train: {:.2%}'.format(svm1.score(X_train, y_train)))
print('svm acc on test: {:.2%}'.format(svm1.score(X_test, y_test)))

svm acc on train: 81.94%
svm acc on test: 84.25%


In [36]:
b=[[0.616,0.999,0.781,0.00001,0.4719,0.0005,0.6306,0.3696,0.0415,0.0022,0.2770,0.9532,0,1.1,0.7021,0.0029,0.0345]]

In [37]:
b_trns=scaler1.transform(b)
b_trns

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[ 0.77180473,  0.97523232,  0.9003833 , -0.        ,  0.46878615,
         0.        ,  0.28705302,  0.3696    ,  0.08202934,  0.        ,
         0.14518228,  0.        , -2.69984748,  0.        ,  0.68655891,
         0.        ,  0.0325461 ]])

In [38]:
svm1.predict(b_trns)

array([1])

In [39]:
svm1.intercept_.round(2)

array([3.51])

In [40]:
svm1.coef_.round(2)

array([[-2.39,  3.02, -1.27, -0.01, -2.2 , -0.  ,  1.21,  3.02, -0.16,
         0.9 , -1.73,  0.05, -5.17, -0.04, -0.01, -0.57, -3.14]])

## controlling the complexity of svm by change parameter 'C'

In [41]:
LinearSVC()

LinearSVC()

In [42]:
C_range=[.1,1,5,10,50,100]

In [43]:
train_scores_SVM, test_scores_SVM=validation_curve(LinearSVC(random_state=0, max_iter=100000), X_bank_trns, y_bank, param_name='C',
                                           param_range=[.1,1,5,10,50,100], cv=4)

In [44]:
train_scores_SVM.round(4)

array([[0.7927, 0.818 , 0.786 , 0.79  ],
       [0.8233, 0.8247, 0.8193, 0.8167],
       [0.826 , 0.8273, 0.8293, 0.822 ],
       [0.83  , 0.826 , 0.8267, 0.8233],
       [0.8307, 0.8287, 0.8247, 0.8247],
       [0.8293, 0.8287, 0.8227, 0.8227]])

In [45]:
print('ave cross in 4 folds for different C values:')
print('training:', train_scores_SVM.mean(axis=1).round(4))
print('test', test_scores_SVM.mean(axis=1).round(4))

ave cross in 4 folds for different C values:
training: [0.7967 0.821  0.8262 0.8265 0.8272 0.8258]
test [0.797  0.8205 0.8225 0.8215 0.824  0.823 ]


In [46]:
train_scores_SVM.mean()

0.8205555555555555

# Decision tree

In [47]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel, y_bank, test_size=0.2, random_state=0)

In [48]:
X_train

Realized Sales Gross Margin   Operating Profit Rate  \
1270                      0.607698                0.999075   
6201                      0.591022                0.998626   
1639                      0.590856                0.998732   
3872                      0.602524                0.999032   
5443                      0.603511                0.999023   
...                            ...                     ...   
4916                      0.601183                0.999023   
6411                      0.600989                0.998889   
4491                      0.616930                0.999190   
3316                      0.625168                0.999191   
5471                      0.619777                0.999209   

       Continuous interest rate (after tax)   Operating Expense Rate  \
1270                               0.781581             1.204932e-04   
6201                               0.781222             3.020425e-04   
1639                               0.781208             1.927660e-04   
3872                               0.781622             7.990000e+08   
5443                               0.781639             1.045354e-04   
...                                     ...                      ...   
4916                               0.781632             6.760000e+09   
6411                               0.781362             1.984322e-04   
4491                               0.781618             1.525245e-04   
3316                               0.781735             2.840032e-04   
5471                               0.781831             1.798147e-04   

       Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
1270         0.465501                0.000447                 0.634492   
6201         0.478040                0.000429                 0.629540   
1639         0.458967                0.000388                 0.629974   
3872         0.484796                0.000414                 0.633260   
5443         0.469698                0.000438                 0.630630   
...               ...                     ...                      ...   
4916         0.460872                0.000424                 0.630873   
6411         0.458103                0.000367                 0.630012   
4491         0.463412                0.000484                 0.633105   
3316         0.483070                0.000465                 0.630703   
5471         0.475044                0.000551                 0.630620   

       Borrowing dependency   Net Worth Turnover Rate (times)  \
1270               0.392679                          0.037097   
6201               0.374118                          0.012903   
1639               0.379328                          0.024355   
3872               0.379072                          0.023065   
5443               0.369637                          0.026452   
...                     ...                               ...   
4916               0.374808                          0.036129   
6411               0.391831                          0.049032   
4491               0.372200                          0.012258   
3316               0.369637                          0.018710   
5471               0.369850                          0.032742   

       Allocation rate per person   Inventory/Working Capital  \
1270                     0.035477                    0.276596   
6201                     0.035610                    0.276956   
1639                     0.013620                    0.276177   
3872                     0.020758                    0.277173   
5443                     0.003649                    0.277012   
...                           ...                         ...   
4916                     0.006172                    0.277277   
6411                     0.006413                    0.278349   
4491                     0.042561                    0.277020   
3316                     0.008820                    0.277028   
5471        

In [49]:
train_scores_decision_tree, test_scores_decision_tree=validation_curve(DecisionTreeClassifier(random_state=0), X_train, y_train, param_name='max_leaf_nodes', 
                                          param_range=[2,6,8,10,15,25,50], cv=5)

In [50]:
dt0=DecisionTreeClassifier(random_state=0, max_leaf_nodes=10)
dt0.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [51]:
print('dt0 acc on train: {:.2%}'.format(dt0.score(X_train, y_train)))
print('dt0 acc on test: {:.2%}'.format(dt0.score(X_test, y_test)))

dt0 acc on train: 90.19%
dt0 acc on test: 89.50%


In [52]:
p1=[0.616,0.999,0.781,0.0001,0.471,0.0005,0.631,0.3696,0.0415,0.0022,0.27698,0,0.953,0,0.7022,0.0029,0.0345]
dt0.predict([p1])

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

## visulalzing our decision tree

In [53]:
export_graphviz(dt0, out_file='dt0_vis.dot', feature_names=X_bank_sel.columns, class_names=dt0.classes_.astype(str), impurity=False, filled=True)

In [54]:
dt0.classes_

array([0, 1])

## Feature Importance 

In [55]:
dt0.feature_importances_.round(3)

array([0.027, 0.043, 0.567, 0.   , 0.   , 0.049, 0.124, 0.   , 0.024,
       0.   , 0.   , 0.027, 0.   , 0.027, 0.   , 0.   , 0.111])

In [56]:
X_bank_sel.columns

Index([' Realized Sales Gross Margin', ' Operating Profit Rate',
       ' Continuous interest rate (after tax)', ' Operating Expense Rate',
       ' Cash flow rate', ' Net Value Growth Rate', ' Interest Expense Ratio',
       ' Borrowing dependency', ' Net Worth Turnover Rate (times)',
       ' Allocation rate per person', ' Inventory/Working Capital',
       ' Inventory/Current Liability', ' Retained Earnings to Total Assets',
       ' Cash Turnover Rate', ' Current Liability to Liability',
       ' Total assets to GNP price', ' Equity to Liability'],
      dtype='object')

In [57]:
feat_imp=pd.DataFrame(data=dt0.feature_importances_.round(3),index=X_bank_sel.columns, columns=['importance'])
feat_imp.sort_values('importance', ascending=False)

importance
 Continuous interest rate (after tax)       0.567
 Interest Expense Ratio                     0.124
 Equity to Liability                        0.111
 Net Value Growth Rate                      0.049
 Operating Profit Rate                      0.043
 Cash Turnover Rate                         0.027
 Inventory/Current Liability                0.027
 Realized Sales Gross Margin                0.027
 Net Worth Turnover Rate (times)            0.024
 Borrowing dependency                       0.000
 Allocation rate per person                 0.000
 Inventory/Working Capital                  0.000
 Cash flow rate                             0.000
 Retained Earnings to Total Assets          0.000
 Operating Expense Rate                     0.000
 Current Liability to Liability             0.000
 Total assets to GNP price                  0.000

# Random Forest

In [60]:
bank_rf=RandomForestClassifier(n_estimators=200, random_state=0)
bank_rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=0)

In [61]:
print('bank_rf on train: {:.2%}'.format(bank_rf.score(X_train, y_train)))
print('bank_rf on test: {:.2%}'.format(bank_rf.score(X_test, y_test)))

bank_rf on train: 100.00%
bank_rf on test: 96.25%


## Feature Importance

In [62]:
bank_rf.feature_importances_

array([0.03503557, 0.0426545 , 0.13722152, 0.01963926, 0.03794655,
       0.08491031, 0.0812242 , 0.12002238, 0.02225733, 0.0336561 ,
       0.03519318, 0.02242399, 0.13672654, 0.02685867, 0.01945017,
       0.02654615, 0.11823357])

In [65]:
bank_rf_feat_imp=pd.DataFrame(data=bank_rf.feature_importances_, index=X_bank_sel.columns, columns=['importance'])
bank_rf_feat_imp.sort_values(by=['importance'], ascending=False).round(3)

importance
 Continuous interest rate (after tax)       0.137
 Retained Earnings to Total Assets          0.137
 Borrowing dependency                       0.120
 Equity to Liability                        0.118
 Net Value Growth Rate                      0.085
 Interest Expense Ratio                     0.081
 Operating Profit Rate                      0.043
 Cash flow rate                             0.038
 Inventory/Working Capital                  0.035
 Realized Sales Gross Margin                0.035
 Allocation rate per person                 0.034
 Cash Turnover Rate                         0.027
 Total assets to GNP price                  0.027
 Inventory/Current Liability                0.022
 Net Worth Turnover Rate (times)            0.022
 Operating Expense Rate                     0.020
 Current Liability to Liability             0.019

In [86]:
X_test.iloc[20:25,:]

Realized Sales Gross Margin   Operating Profit Rate  \
1176                      0.595007                0.998909   
948                       0.610595                0.998977   
4446                      0.611936                0.999137   
1756                      0.623013                0.998633   
1756                      0.623013                0.998633   

       Continuous interest rate (after tax)   Operating Expense Rate  \
1176                               0.781286             8.270000e+09   
948                                0.781531             2.649232e-04   
4446                               0.781773             1.265063e-04   
1756                               0.781034             8.084147e-04   
1756                               0.781034             8.084147e-04   

       Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
1176         0.461918                0.000404                 0.628257   
948          0.461711                0.000441                 0.624179   
4446         0.457142                0.000814                 0.630616   
1756         0.486569                0.000390                 0.630274   
1756         0.486569                0.000390                 0.630274   

       Borrowing dependency   Net Worth Turnover Rate (times)  \
1176               0.384412                          0.023548   
948                0.379319                          0.037258   
4446               0.378273                          0.105323   
1756               0.373629                          0.019355   
1756               0.373629                          0.019355   

       Allocation rate per person   Inventory/Working Capital  \
1176                     0.086678                    0.278969   
948                      0.004766                    0.277887   
4446                     0.005009                    0.274562   
1756                     0.000385                    0.277069   
1756                     0.000385                    0.277069   

       Inventory/Current Liability   Retained Earnings to Total Assets  \
1176                      0.015562                            0.923034   
948                       0.006438                            0.932147   
4446                      0.002208                            0.951260   
1756                      0.003182                            0.892959   
1756                      0.003182                            0.892959   

       Cash Turnover Rate   Current Liability to Liability  \
1176         2.430000e+09                         0.707643   
948          4.840000e+09                         0.909853   
4446         3.260000e+09                         0.988181   
1756         9.330000e+07                         0.486479   
1756         9.330000e+07                         0.486479   

       Total assets to GNP price   Equity to Liability  
1176                    0.013448              0.020525  
948                     0.001133              0.020014  
4446                    0.000884              0.016198  
1756                    0.000440              0.031375  
1756                    0.000440              0.031375

In [87]:
bank_rf.predict(X_test.iloc[20:25,:])

array([1, 1, 0, 1, 1])

# KNN Classifier

In [69]:
train_scores_KNN, test_scores_KNN=validation_curve(KNeighborsClassifier(), X_bank_trns, y_bank, param_name='n_neighbors', 
                                           param_range=[1,2,3,4,5,6], cv=4)

In [70]:
train_scores_KNN.mean(axis=1)

array([1.        , 0.99      , 0.93683333, 0.91983333, 0.88983333,
       0.874     ])

In [71]:
train_scores_KNN.mean()

0.9350833333333334

In [72]:
test_scores_KNN.mean()

0.86775

In [73]:
X_train, X_test, y_train, y_test=train_test_split(X_bank_sel,y_bank,
                                                  random_state=0)

In [74]:
knn_cls_bank_bal=KNeighborsClassifier(n_neighbors=5)

In [75]:
knn_cls_bank_bal.fit(X_train,y_train)

KNeighborsClassifier()

In [76]:
print('knn_cls_bank_bal acc on train: {:.2%}'.format(knn_cls_bank_bal.score(X_train,y_train)))
print('knn_cls_bank_bal acc on test: {:.2%}'.format(knn_cls_bank_bal.score(X_test,y_test)),'\n')

knn_cls_bank_bal acc on train: 83.40%
knn_cls_bank_bal acc on test: 78.60% 



In [77]:
knn_cls_bank_bal.score(X_bank_sel,y_bank)

0.822

In [78]:
w1=[1,1,0.5,0.4,0.3,0.3,0.6,0.7,1,0.4,0.2,0.5,0.7,0.4,0.1,0.9,0.6]
knn_cls_bank_bal.predict([w1])

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

In [79]:
knn_cls_bank_bal.predict(X_bank_sel)

array([1, 0, 0, ..., 1, 1, 1])

In [80]:
len(knn_cls_bank_bal.predict(X_bank_sel))

2000

In [91]:
predict_array = knn_cls_bank_bal.predict(X_bank_sel)
count_non_zero = 0
for i in predict_array:
    if i != 0:
        count_non_zero += 1
print(count_non_zero)      

1198


In [95]:
sum(knn_cls_bank_bal.predict(X_bank_sel))

1198

In [85]:
X_bank_sel.describe()

Realized Sales Gross Margin   Operating Profit Rate  \
count                   2000.000000             2000.000000   
mean                       0.603785                0.998843   
std                        0.014686                0.000993   
min                        0.449761                0.973424   
25%                        0.597580                0.998857   
50%                        0.602099                0.998976   
75%                        0.609738                0.999044   
max                        0.665151                0.999650   

        Continuous interest rate (after tax)   Operating Expense Rate  \
count                            2000.000000             2.000000e+03   
mean                                0.781041             1.844045e+09   
std                                 0.003344             3.190004e+09   
min                                 0.735093             1.000256e-04   
25%                                 0.781286             1.549529e-04   
50%                                 0.781541             2.864894e-04   
75%                                 0.781652             3.202500e+09   
max                                 0.786079             9.980000e+09   

        Cash flow rate   Net Value Growth Rate   Interest Expense Ratio  \
count      2000.000000            2.000000e+03              2000.000000   
mean          0.464422            3.732000e+07                 0.631498   
std           0.012146            5.890469e+08                 0.014577   
min           0.343818            0.000000e+00                 0.525126   
25%           0.459606            3.896315e-04                 0.630095   
50%           0.462599            4.406694e-04                 0.630612   
75%           0.466664            4.735780e-04                 0.631087   
max           0.617039            9.330000e+09                 0.892562   

        Borrowing dependency   Net Worth Turnover Rate (times)  \
count            2000.000000                       2000.000000   
mean                0.382959                          0.039831   
std                 0.052685                          0.036178   
min                 0.000000                          0.009032   
25%                 0.371918                          0.021935   
50%                 0.376805                          0.029839   
75%                 0.383465                          0.043750   
max                 1.000000                          0.404839   

        Allocation rate per person   Inventory/Working Capital  \
count                 2.000000e+03                 2000.000000   
mean                  3.480000e+06                    0.277368   
std                   1.100197e+08                    0.005311   
min                   0.000000e+00                    0.244753   
25%                   4.761171e-03                    0.276920   
50%                   1.027135e-02                    0.277135   
75%                   2.309766e-02                    0.277511   
max                   3.480000e+09                    0.466868   

        Inventory/Current Liability   Retained Earnings to Total Assets  \
count                  2.000000e+03                         2000.000000   
mean                   3.585150e+07                            0.919430   
std                    4.840476e+08                            0.034846   
min                    0.000000e+00                            0.728885   
25%                    2.487101e-03                            0.909662   
50%                    5.344259e-03                            0.930045   
75%                    9.879049e-03                            0.938763   
max                    9.910000e+09                            0.998858   

        Cash Turnover Rate   Current Liability to Liability  \
count         2.000000e+03                      2000.000000   
mean          2.332955e+09                         0.748211   
std           2.687308e+09                         